(function initManttoLabSalesCollectionsRoutes(root,factory){
  const api=factory(root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.ManttoLabSalesCollectionsRoutes=api;
})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabSalesCollectionsRoutes(root){
  'use strict';

  const SALES_GROUP='VENTAS',COR_GROUP='COBRANZA',UNI_GROUP='COBRANZA_UNI';
  const QUOTE_DETAIL=Object.freeze([
    'VENTAS_COTIZACIONES_TABLA_COTIZACIONES_DETALLE_COTIZACION.VER',
    'VENTAS_COTIZACIONES_TABLA_COTIZACIONES_LISTADO_COTIZACIONES.ABRIR_DETALLE',
    'VENTAS_VENDIDOS_TABLA_COTIZACIONES_VENDIDAS_LISTADO.ABRIR_DETALLE',
    'VENTAS_PERDIDOS_TABLA_COTIZACIONES_PERDIDAS_LISTADO.ABRIR_DETALLE',
    'VENTAS_PROYECCION_TABLA_COTIZACIONES_POR_ESTATUS_LISTADO.ABRIR_DETALLE',
    'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_RELACION_COTIZACION.ABRIR_DETALLE',
    'VENTAS_DASHBOARD_TABLAS_CONSULTA_COTIZACIONES.ABRIR_DETALLE',
    'VENTAS_DASHBOARD_TABLAS_CONSULTA_VENDIDOS.ABRIR_DETALLE',
    'VENTAS_DASHBOARD_TABLAS_CONSULTA_PERDIDOS.ABRIR_DETALLE'
  ]);
  const CLIENT_DETAIL=Object.freeze(['VENTAS_CLIENTES_TABLA_CLIENTES_DETALLE_CLIENTE.VER','VENTAS_CLIENTES_TABLA_CLIENTES_LISTADO_CLIENTES.ABRIR_DETALLE']);
  const PROSPECT_DETAIL=Object.freeze(['VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.VER','VENTAS_PROSPECCION_TABLA_VISITAS_LISTADO.ABRIR_DETALLE','VENTAS_MAPA_PROSPECCION_MAPA_VISITAS_MARCADORES.ABRIR_DETALLE','VENTAS_DASHBOARD_TABLAS_CONSULTA_PROSPECCION.ABRIR_DETALLE']);
  const NETWORK_DETAIL=Object.freeze(['VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_DETALLE.VER','VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_LISTADO.ABRIR_DETALLE']);
  const DASH_COMMERCIAL=Object.freeze({
    clientes:'VENTAS_DASHBOARD_TABLAS_CONSULTA_CLIENTES.VER',
    cotizaciones:'VENTAS_DASHBOARD_TABLAS_CONSULTA_COTIZACIONES.VER',
    ventas:'VENTAS_DASHBOARD_TABLAS_CONSULTA_VENDIDOS.VER',
    perdido:'VENTAS_DASHBOARD_TABLAS_CONSULTA_PERDIDOS.VER',
    prospeccion:'VENTAS_DASHBOARD_TABLAS_CONSULTA_PROSPECCION.VER',
    redes:'VENTAS_DASHBOARD_TABLAS_CONSULTA_ASIGNACION_REDES.VER'
  });
  const DASH_OPERATIONAL=Object.freeze({
    instalaciones:'VENTAS_DASHBOARD_TABLAS_CONSULTA_INSTALACIONES.VER',
    logistica:'VENTAS_DASHBOARD_TABLAS_CONSULTA_LOGISTICA.VER',
    tareas_asignadas:'VENTAS_DASHBOARD_TABLAS_CONSULTA_TAREAS_ASIGNADAS.VER',
    tareas_creadas:'VENTAS_DASHBOARD_TABLAS_CONSULTA_TAREAS_CREADAS.VER'
  });

  function services(){const s={sales:root?.ManttoLabSalesService,uni:root?.ManttoLabCollectionsUniService,cor:root?.ManttoLabCollectionsCorService,permissions:root?.ManttoLabPermissionsService,scope:root?.ManttoLabScopeService};if(Object.values(s).some(v=>!v))throw new Error('MANTTO_LAB_PHASE8_SERVICES_REQUIRED');return s;}
  function actor(req){return req.actorUser||req.context?.actorUser||req.user||null;}
  function effective(req){return req.contextUser||req.user||req.context?.contextUser||req.context?.user||null;}
  function userId(req){return Number(effective(req)?.id_SB||0);}
  function requireAuth(req,res,next){const fn=root?.ManttoLabAuthPermissionRoutes?.requireAuth;if(typeof fn==='function')return fn(req,res,next);if(!actor(req))return res.status(401).json({ok:false,message:'Selecciona una identidad de Laboratorio DGB.',code:'LAB_IDENTITY_REQUIRED'});return next();}
  function group(groupCode,db){return db.query('SELECT id_agrupacion,codigo,nombre,empresa FROM perm_agrupaciones WHERE activo=1 AND UPPER(TRIM(codigo))=? LIMIT 1',[String(groupCode).toUpperCase()])[0]||null;}
  function gate(codes,groupCode){const required=Array.isArray(codes)?codes:[codes];return function phase8Gate(req,res,next){const uid=userId(req);if(!uid)return res.status(401).json({ok:false,message:'Selecciona una identidad de Laboratorio DGB.',code:'LAB_IDENTITY_REQUIRED'});const functional=required.some(code=>services().permissions.hasEffectivePermission(uid,code,req.db));if(!functional)return res.status(403).json({ok:false,message:'No tienes autorización funcional para esta información.',code:'LAB_FUNCTIONAL_PERMISSION_DENIED'});const g=group(groupCode,req.db);if(!g||!services().scope.groupAllowed(uid,Number(g.id_agrupacion),req.db))return res.status(403).json({ok:false,message:'El permiso existe, pero el alcance de información no abre la agrupación correspondiente.',code:'LAB_INFORMATION_GATE_DENIED'});return next();};}
  function allCodes(map){return Object.values(map);}
  function wrap(data){return{ok:true,source:'lab-sqlite',data};}
  function local501(req,res){return res.status(501).json({ok:false,code:'LAB_MOCK_NOT_IMPLEMENTED',message:'La integración/sincronización productiva está deshabilitada en Laboratorio DGB.'});}
  function has(req,code){return services().permissions.hasEffectivePermission(userId(req),code,req.db);}
  function filterAuthorizedTables(req,payload,map){const out={};for(const [key,code] of Object.entries(map))if(has(req,code))out[key]=payload?.tablas?.[key]||[];return{...payload,tablas:out};}
  function quoteFileMetadata(req){const rows=services().sales.listQuoteFiles(userId(req),req.params.id,req.db);return rows.find(r=>Number(r.id_archivo)===Number(req.params.idArchivo))||null;}
  function maybeAssigned(value){const n=Number(value);return Number.isInteger(n)&&n>0?n:null;}

  function register(router){
    if(!router||typeof router.get!=='function')throw new Error('MANTTO_LAB_ROUTER_REQUIRED');
    if(router.__manttoLabPhase8V002Routes)return router;router.__manttoLabPhase8V002Routes=true;

    // Dashboard Ventas.
    router.get('/api/ventas/dashboard/usuarios',requireAuth,gate('VENTAS_DASHBOARD_SELECTOR_RESPONSABLE_COMERCIAL.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.dashboardUsers(userId(req),req.db)}));
    router.get('/api/ventas/dashboard/kpis',requireAuth,gate('VENTAS_DASHBOARD_KPI_COMERCIALES_INDICADORES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.dashboardKpis(userId(req),req.query,req.db)}));
    router.get('/api/ventas/dashboard/tablas',requireAuth,gate(allCodes(DASH_COMMERCIAL),SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...filterAuthorizedTables(req,services().sales.dashboardTables(userId(req),req.query,req.db),DASH_COMMERCIAL)}));
    router.get('/api/ventas/dashboard/operacion',requireAuth,gate(allCodes(DASH_OPERATIONAL),SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...filterAuthorizedTables(req,services().sales.dashboardOperation(userId(req),req.query,req.db),DASH_OPERATIONAL)}));
    router.get('/api/ventas/dashboard/pdf/capabilities',requireAuth,gate('VENTAS_DASHBOARD_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',fase:'LAB_F8',pdf:{general:has(req,'VENTAS_DASHBOARD_PDF_REPORTES.GENERAR_PDF_GENERAL'),individual:has(req,'VENTAS_DASHBOARD_PDF_REPORTES.GENERAR_PDF_INDIVIDUAL')},browser_pdf:true,server_file:false}));
    const pdfGate=(req,res,next)=>gate(String(req.query?.tipo||'GENERAL').toUpperCase()==='INDIVIDUAL'?'VENTAS_DASHBOARD_PDF_REPORTES.GENERAR_PDF_INDIVIDUAL':'VENTAS_DASHBOARD_PDF_REPORTES.GENERAR_PDF_GENERAL',SALES_GROUP)(req,res,next);
    router.get('/api/ventas/dashboard/pdf/prepare',requireAuth,pdfGate,(req,res)=>res.json(services().sales.dashboardPdfData(userId(req),req.query,req.db)));
    router.get('/api/ventas/dashboard/pdf/data',requireAuth,pdfGate,(req,res)=>res.json(services().sales.dashboardPdfData(userId(req),req.query,req.db)));

    // Clientes y contactos.
    router.post('/api/ventas/clientes/sync',requireAuth,local501);
    router.get('/api/ventas/clientes/catalogos',requireAuth,gate('VENTAS_CLIENTES_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:services().sales.clientCatalogs(userId(req),req.db)}));
    router.get('/api/ventas/clientes/asesores-asignables',requireAuth,gate('VENTAS_CLIENTES_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',mode:services().sales.visibleUserIds(userId(req),req.db)===null?'ALL':'LIMITED',data:services().sales.visibleCommercialUsers(userId(req),req.db).map(row=>({id_usuario:Number(row.id_SB),nombre:row.nombre||'',iniciales:row.iniciales||'',puesto:row.puesto||null,etiqueta:row.nombre?`${row.iniciales||''} · ${row.nombre}`:(row.iniciales||'')}))}));
    router.get('/api/ventas/clientes/kpis',requireAuth,gate('VENTAS_CLIENTES_KPI_INDICADORES_CLIENTES.VER',SALES_GROUP),(req,res)=>{const result=services().sales.listClients(userId(req),{...req.query,page:1,page_size:100},req.db),rows=result.clientes;return res.json({ok:true,source:'lab-sqlite',kpis:{total_clientes:Number(result.pagination?.total??rows.length),con_estatus:rows.filter(r=>String(r.estatus_cliente||'').trim()).length,con_proyecto_vendido:rows.filter(r=>Number(r.vendidas||0)>0||String(r.proyecto_vendido||'').trim()).length,tipos_cliente:new Set(rows.map(r=>String(r.tipo_cliente||'').trim()).filter(Boolean)).size,estados:new Set(rows.map(r=>String(r.estado||'').trim()).filter(Boolean)).size}});});
    router.get('/api/ventas/clientes',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_LISTADO_CLIENTES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listClients(userId(req),req.query,req.db)}));
    router.get('/api/ventas/clientes/:id',requireAuth,gate(CLIENT_DETAIL,SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',cliente:services().sales.getClient(userId(req),req.params.id,req.db)}));
    router.post('/api/ventas/clientes',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_NUEVO_CLIENTE.CREAR',SALES_GROUP),(req,res)=>{const row=services().sales.createClient(req.body||{},actor(req),req.db);return res.status(201).json({ok:true,source:'lab-sqlite',id_cliente:Number(row.id_cliente)});});
    router.put('/api/ventas/clientes/:id',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CLIENTE.EDITAR',SALES_GROUP),(req,res)=>{const row=services().sales.updateClient(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.json({ok:true,source:'lab-sqlite',id_cliente:Number(row.id_cliente)});});
    router.patch('/api/ventas/clientes/:id',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CLIENTE.EDITAR',SALES_GROUP),(req,res)=>{const row=services().sales.updateClient(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.json({ok:true,source:'lab-sqlite',id_cliente:Number(row.id_cliente)});});
    router.delete('/api/ventas/clientes/:id',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CLIENTE.EDITAR',SALES_GROUP),(req,res)=>{const row=services().sales.removeClient(userId(req),req.params.id,actor(req),req.db);return res.json({ok:true,source:'lab-sqlite',id_cliente:Number(row.id_cliente),eliminado:true});});
    router.get('/api/ventas/clientes/:id/contactos',requireAuth,gate(CLIENT_DETAIL,SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',data:services().sales.listContacts(userId(req),req.params.id,req.db)}));
    router.post('/api/ventas/clientes/:id/contactos',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_NUEVO_CONTACTO.CREAR',SALES_GROUP),(req,res)=>res.status(201).json(wrap(services().sales.createContact(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.put('/api/ventas/clientes/:id/contactos/:idContacto',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CONTACTO.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateContact(userId(req),req.params.id,req.params.idContacto,req.body||{},actor(req),req.db))));
    router.patch('/api/ventas/clientes/:id/contactos/:idContacto',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CONTACTO.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateContact(userId(req),req.params.id,req.params.idContacto,req.body||{},actor(req),req.db))));
    router.patch('/api/ventas/clientes/:id/contactos/:idContacto/principal',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_EDITAR_CONTACTO.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.setPrincipalContact(userId(req),req.params.id,req.params.idContacto,actor(req),req.db))));
    router.delete('/api/ventas/clientes/:id/contactos/:idContacto',requireAuth,gate('VENTAS_CLIENTES_TABLA_CLIENTES_DESACTIVAR_CONTACTO.DESACTIVAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.removeContact(userId(req),req.params.id,req.params.idContacto,actor(req),req.db))));

    // Cotizaciones, Vendidos, Perdidos y Proyección.
    router.post('/api/ventas/cotizaciones/sync',requireAuth,local501);router.post('/api/ventas/cotizaciones/comentarios/sync',requireAuth,local501);
    router.get('/api/ventas/cotizaciones/catalogos',requireAuth,gate(['VENTAS_COTIZACIONES_ACCESO_VISUAL_MODULO.ACCESO_VISUAL','VENTAS_VENDIDOS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL','VENTAS_PERDIDOS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL','VENTAS_PROYECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL'],SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:services().sales.quoteCatalogs(userId(req),req.db)}));
    router.get('/api/ventas/cotizaciones/kpis',requireAuth,gate('VENTAS_COTIZACIONES_KPI_INDICADORES_COTIZACIONES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.kpisQuotes(userId(req),req.query,req.db)}));
    router.get('/api/ventas/cotizaciones/embudo',requireAuth,gate(['VENTAS_COTIZACIONES_KPI_INDICADORES_COTIZACIONES.VER','VENTAS_PROYECCION_BOTONES_KPI_ETAPAS.VER'],SALES_GROUP),(req,res)=>{const rows=services().sales.listQuotes(userId(req),{...req.query,page:1,page_size:100},req.db).cotizaciones;const embudo=services().sales.ACTIVE_QUOTE_STATUSES.map(estatus=>({estatus,cotizaciones:rows.filter(row=>String(row.estatus_proyecto||'')===estatus).length,equipos:rows.filter(row=>String(row.estatus_proyecto||'')===estatus).reduce((sum,row)=>sum+Number(row.numero_equipos||0),0)}));return res.json({ok:true,source:'lab-sqlite',embudo,data:embudo});});
    router.get('/api/ventas/cotizaciones/vendidos',requireAuth,gate('VENTAS_VENDIDOS_TABLA_COTIZACIONES_VENDIDAS_LISTADO.VER',SALES_GROUP),(req,res)=>{const rows=services().sales.quoteByStatus(userId(req),['Vendido'],req.query,req.db);return res.json({ok:true,source:'lab-sqlite',vendidos:rows,data:rows});});
    router.get('/api/ventas/cotizaciones/perdidos',requireAuth,gate('VENTAS_PERDIDOS_TABLA_COTIZACIONES_PERDIDAS_LISTADO.VER',SALES_GROUP),(req,res)=>{const rows=services().sales.quoteByStatus(userId(req),['Perdido'],req.query,req.db);return res.json({ok:true,source:'lab-sqlite',perdidos:rows,data:rows});});
    router.get('/api/ventas/cotizaciones/proyeccion',requireAuth,gate('VENTAS_PROYECCION_TABLA_COTIZACIONES_POR_ESTATUS_LISTADO.VER',SALES_GROUP),(req,res)=>{const rows=services().sales.quoteDashboardProjection(userId(req),req.query,req.db);return res.json({ok:true,source:'lab-sqlite',proyeccion:rows,data:rows});});
    router.get('/api/ventas/cotizaciones/proyectos-interes',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_LISTADO_COTIZACIONES.VER',SALES_GROUP),(req,res)=>res.json(services().sales.listInterests(userId(req),req.query,req.db)));
    router.get('/api/ventas/cotizaciones/historial',requireAuth,gate('VENTAS_PROYECCION_TABLA_COTIZACIONES_POR_ESTATUS_HISTORIAL.VER_HISTORIAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listHistory(userId(req),null,req.query,req.db)}));
    router.get('/api/ventas/cotizaciones/:id/historial',requireAuth,gate('VENTAS_PROYECCION_TABLA_COTIZACIONES_POR_ESTATUS_HISTORIAL.VER_HISTORIAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listHistory(userId(req),req.params.id,req.query,req.db)}));
    router.get('/api/ventas/cotizaciones',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_LISTADO_COTIZACIONES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listQuotes(userId(req),req.query,req.db)}));
    router.get('/api/ventas/cotizaciones/:id/comentarios',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',data:services().sales.listQuoteComments(userId(req),req.params.id,req.db)}));
    router.post('/api/ventas/cotizaciones/:id/comentarios',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_DETALLE_COTIZACION.AGREGAR_COMENTARIO',SALES_GROUP),async(req,res)=>res.status(201).json(wrap(await services().sales.addQuoteComment(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.patch('/api/ventas/cotizaciones/:id/comentarios/:idComentario',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateQuoteComment(userId(req),req.params.id,req.params.idComentario,req.body||{},actor(req),req.db))));
    router.delete('/api/ventas/cotizaciones/:id/comentarios/:idComentario',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),async(req,res)=>res.json(wrap(await services().sales.removeQuoteComment(userId(req),req.params.id,req.params.idComentario,actor(req),req.db))));
    router.get('/api/ventas/cotizaciones/:id/archivos',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',data:services().sales.listQuoteFiles(userId(req),req.params.id,req.db)}));
    router.post('/api/ventas/cotizaciones/:id/archivos',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_DETALLE_COTIZACION.ADJUNTAR_ARCHIVO',SALES_GROUP),async(req,res)=>res.status(201).json(wrap(await services().sales.addQuoteFile(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.get('/api/ventas/cotizaciones/:id/archivos/:idArchivo/acceso',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),async(req,res)=>res.json(wrap(await services().sales.quoteFileAccess(userId(req),req.params.id,req.params.idArchivo,req.db))));
    router.get('/api/ventas/cotizaciones/:id/archivos/:idArchivo',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),(req,res)=>{const row=quoteFileMetadata(req);return row?res.json(wrap(row)):res.status(404).json({ok:false,message:'Archivo no encontrado.'});});
    router.patch('/api/ventas/cotizaciones/:id/archivos/:idArchivo',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),(req,res)=>{const row=quoteFileMetadata(req);if(!row)return res.status(404).json({ok:false,message:'Archivo no encontrado.'});req.db.run('UPDATE ventas_cotizaciones_archivos SET tipo_archivo=?,descripcion=?,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[String(req.body?.tipo_archivo??row.tipo_archivo??''),String(req.body?.descripcion??row.descripcion??''),Number(row.id_archivo)]);return res.json(wrap(quoteFileMetadata(req)));});
    router.delete('/api/ventas/cotizaciones/:id/archivos/:idArchivo',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),async(req,res)=>res.json(wrap(await services().sales.removeQuoteFile(userId(req),req.params.id,req.params.idArchivo,actor(req),req.db))));
    router.patch('/api/ventas/cotizaciones/:id/estatus',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_DETALLE_COTIZACION.CAMBIAR_ESTADO',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateQuoteStatus(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.patch('/api/ventas/cotizaciones/:id/asignacion',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateQuoteAssignment(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.get('/api/ventas/cotizaciones/:id/editar-bootstrap',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',data:{cotizacion:services().sales.getQuote(userId(req),req.params.id,req.db),catalogos:services().sales.quoteCatalogs(userId(req),req.db)}}));
    router.get('/api/ventas/cotizaciones/:id/interes',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),(req,res)=>res.json(services().sales.getInterest(userId(req),req.params.id,req.db)));
    router.put('/api/ventas/cotizaciones/:id/interes',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),async(req,res)=>res.json(await services().sales.setInterest(userId(req),req.params.id,req.body?.activo??req.body?.proyecto_interes,actor(req),req.db)));
    router.get('/api/ventas/cotizaciones/:id',requireAuth,gate(QUOTE_DETAIL,SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',cotizacion:services().sales.getQuote(userId(req),req.params.id,req.db)}));
    router.post('/api/ventas/cotizaciones',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_NUEVA_COTIZACION.CREAR',SALES_GROUP),(req,res)=>res.status(201).json(wrap(services().sales.createQuote(req.body||{},actor(req),req.db))));
    router.put('/api/ventas/cotizaciones/:id',requireAuth,gate('VENTAS_COTIZACIONES_TABLA_COTIZACIONES_EDITAR_COTIZACION.EDITAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.updateQuote(userId(req),req.params.id,req.body||{},actor(req),req.db))));
    router.delete('/api/ventas/cotizaciones/:id',requireAuth,gate('VENTAS_COTIZACIONES_OPERACION.ELIMINAR',SALES_GROUP),(req,res)=>res.json(wrap(services().sales.removeQuote(userId(req),req.params.id,actor(req),req.db))));

    // Prospección.
    router.post('/api/ventas/prospeccion/sync',requireAuth,local501);router.post('/api/ventas/prospeccion/comentarios/sync',requireAuth,local501);
    router.get('/api/ventas/prospeccion/catalogos-captura',requireAuth,gate('VENTAS_PROSPECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:services().sales.prospectCaptureCatalogs(req.db)}));
    router.get('/api/ventas/prospeccion/fuentes',requireAuth,gate('VENTAS_PROSPECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',resultados:services().sales.prospectSources(userId(req),req.query,req.db)}));
    router.get('/api/ventas/prospeccion/contactos',requireAuth,gate('VENTAS_PROSPECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>{const cid=Number(req.query?.id_cliente);if(!Number.isInteger(cid)||cid<=0)return res.status(400).json({ok:false,code:'LAB_CLIENT_ID_REQUIRED',message:'id_cliente es obligatorio.'});return res.json({ok:true,source:'lab-sqlite',contactos:services().sales.prospectContacts(userId(req),cid,req.db)});});
    router.post('/api/ventas/prospeccion',requireAuth,gate('VENTAS_PROSPECCION_TABLA_VISITAS_NUEVA_VISITA.CREAR',SALES_GROUP),async(req,res)=>{const row=await services().sales.createProspect(req.body||{},actor(req),req.db);return res.status(201).json({ok:true,source:'lab-sqlite',id_pros:Number(row.id_pros),prospeccion:row,message:'Visita creada correctamente.'});});
    router.get('/api/ventas/prospeccion/catalogos',requireAuth,gate(['VENTAS_PROSPECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL','VENTAS_MAPA_PROSPECCION_ACCESO_VISUAL_MODULO.ACCESO_VISUAL'],SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:services().sales.prospectCatalogs(userId(req),req.db)}));
    router.get('/api/ventas/prospeccion/kpis',requireAuth,gate('VENTAS_PROSPECCION_KPI_INDICADORES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.prospectKpis(userId(req),req.query,req.db)}));
    router.get('/api/ventas/prospeccion/mapa',requireAuth,gate('VENTAS_MAPA_PROSPECCION_MAPA_VISITAS_MARCADORES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',puntos:services().sales.prospectMap(userId(req),req.query,req.db)}));
    router.get('/api/ventas/prospeccion',requireAuth,gate('VENTAS_PROSPECCION_TABLA_VISITAS_LISTADO.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listProspects(userId(req),req.query,req.db)}));
    router.get('/api/ventas/prospeccion/detalle/catalogos',requireAuth,gate(['VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.VER','VENTAS_MAPA_PROSPECCION_MAPA_VISITAS_MARCADORES.ABRIR_DETALLE'],SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:{estatus:services().sales.prospectCatalogs(userId(req),req.db).estatus}}));
    router.patch('/api/ventas/prospeccion/:id/estatus',requireAuth,gate('VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.CAMBIAR_ESTADO',SALES_GROUP),(req,res)=>{const row=services().sales.updateProspectStatus(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.json({ok:true,source:'lab-sqlite',prospeccion:row,notificaciones_estatus:0});});
    router.patch('/api/ventas/prospeccion/:id/cotizacion',requireAuth,gate('VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.CAMBIAR_ESTADO',SALES_GROUP),(req,res)=>{const result=services().sales.linkProspectQuote(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.json({ok:true,source:'lab-sqlite',...result,notificaciones_estatus:0});});
    router.post('/api/ventas/prospeccion/:id/comentarios',requireAuth,gate('VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.AGREGAR_COMENTARIO',SALES_GROUP),async(req,res)=>{const result=await services().sales.addProspectComment(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.status(201).json({ok:true,source:'lab-sqlite',...result,notificaciones:0});});
    router.get('/api/ventas/prospeccion/:id/archivos/:idArchivo/acceso',requireAuth,gate(PROSPECT_DETAIL,SALES_GROUP),async(req,res)=>{const data=await services().sales.prospectFileAccess(userId(req),req.params.id,req.params.idArchivo,req.db);return res.json({ok:true,source:'lab-sqlite',data,access_url:data.url||null,url:data.url||null});});
    router.delete('/api/ventas/prospeccion/:id/archivos/:idArchivo',requireAuth,gate(['VENTAS_PROSPECCION_TABLA_VISITAS_DETALLE_PROSPECCION.ADJUNTAR_ARCHIVO','VENTAS_PROSPECCION_TABLA_VISITAS_EDITAR_PROSPECCION.EDITAR'],SALES_GROUP),async(req,res)=>res.json({ok:true,source:'lab-sqlite',...(await services().sales.removeProspectFile(userId(req),req.params.id,req.params.idArchivo,req.db))}));
    router.get('/api/ventas/prospeccion/:id',requireAuth,gate(PROSPECT_DETAIL,SALES_GROUP),(req,res)=>{const row=services().sales.getProspect(userId(req),req.params.id,req.db);return res.json({ok:true,source:'lab-sqlite',prospeccion:Object.fromEntries(Object.entries(row).filter(([key])=>!['comentarios','archivos'].includes(key))),comentarios:row.comentarios||[],archivos:(row.archivos||[]).map(file=>({...file,access_endpoint:`/api/ventas/prospeccion/${req.params.id}/archivos/${file.id_archivo}/acceso`}))});});

    // Asignación de Redes.
    router.post('/api/ventas/redes/importar-backup',requireAuth,local501);router.post('/api/ventas/redes/comentarios/importar-backup',requireAuth,local501);
    const redesCanAssign=(req)=>has(req,'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_NUEVA_ASIGNACION.ASIGNAR_RESPONSABLES')||has(req,'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.ASIGNAR_RESPONSABLES');
    router.get('/api/ventas/redes/catalogos',requireAuth,gate('VENTAS_ASIGNACION_REDES_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',catalogos:services().sales.networkCatalogs(userId(req),req.db),puede_asignar:redesCanAssign(req),visibilidad:services().sales.coreScope(userId(req),req.db)}));
    router.get('/api/ventas/redes/usuarios-asignables',requireAuth,gate('VENTAS_ASIGNACION_REDES_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',SALES_GROUP),(req,res)=>{const allowed=redesCanAssign(req);const rows=allowed?services().sales.visibleCommercialUsers(userId(req),req.db).map(row=>({id_usuario:Number(row.id_SB),nombre:row.nombre||'',iniciales:row.iniciales||'',puesto:row.puesto||null,area:row.area||null,empresa:row.empresa||null,etiqueta:row.nombre?`${row.iniciales||''} · ${row.nombre}`:(row.iniciales||'')})):[];return res.json({ok:true,source:'lab-sqlite',puede_asignar:allowed,usuarios:rows});});
    router.get('/api/ventas/redes/cotizaciones-activas',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_RELACION_COTIZACION.VER',SALES_GROUP),(req,res)=>{const rows=services().sales.listQuotes(userId(req),{...req.query,page:1,page_size:100},req.db).cotizaciones.filter(r=>services().sales.ACTIVE_QUOTE_STATUSES.includes(r.estatus_proyecto));return res.json({ok:true,source:'lab-sqlite',cotizaciones:rows});});
    router.get('/api/ventas/redes',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_LISTADO.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.listNetworks(userId(req),req.query,req.db),puede_asignar:redesCanAssign(req),visibilidad:services().sales.coreScope(userId(req),req.db)}));
    router.post('/api/ventas/redes',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_NUEVA_ASIGNACION.CREAR',SALES_GROUP),async(req,res)=>{if(maybeAssigned(req.body?.id_usuario_asignado)&&!has(req,'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_NUEVA_ASIGNACION.ASIGNAR_RESPONSABLES'))return res.status(403).json({ok:false,code:'LAB_FUNCTIONAL_PERMISSION_DENIED',message:'No tienes permiso para asignar responsables al crear registros de Redes.'});const row=await services().sales.createNetwork(req.body||{},actor(req),req.db);return res.status(201).json({ok:true,source:'lab-sqlite',id_redes:Number(row.id_redes),registro:row});});
    router.get('/api/ventas/redes/:id/archivos',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_IMAGENES.VER',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',archivos:services().sales.listNetworkFiles(userId(req),req.params.id,req.db).map(file=>({...file,access_endpoint:`/api/ventas/redes/${req.params.id}/archivos/${file.id_archivo}/acceso`}))}));
    router.post('/api/ventas/redes/:id/archivos',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_IMAGENES.ADJUNTAR_ARCHIVO',SALES_GROUP),async(req,res)=>res.status(201).json({ok:true,source:'lab-sqlite',archivos:await services().sales.uploadNetworkFiles(userId(req),req.params.id,req.body||{},actor(req),req.db)}));
    router.get('/api/ventas/redes/:id/archivos/:idArchivo/acceso',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_IMAGENES.VER',SALES_GROUP),async(req,res)=>{const data=await services().sales.networkFileAccess(userId(req),req.params.id,req.params.idArchivo,req.db);return res.json({ok:true,source:'lab-sqlite',data,access_url:data.url||null,url:data.url||null});});
    router.delete('/api/ventas/redes/:id/archivos/:idArchivo',requireAuth,gate(['VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_IMAGENES.ADJUNTAR_ARCHIVO','VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR'],SALES_GROUP),async(req,res)=>res.json({ok:true,source:'lab-sqlite',...(await services().sales.removeNetworkFile(userId(req),req.params.id,req.params.idArchivo,req.db))}));
    router.get('/api/ventas/redes/:id/comentarios',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_COMENTARIOS.VER',SALES_GROUP),(req,res)=>{const rows=services().sales.listNetworkComments(userId(req),req.params.id,req.db).map(comment=>({...comment,adjuntos:(comment.adjuntos||[]).map(file=>({...file,access_endpoint:`/api/ventas/redes/${req.params.id}/comentarios/${comment.id_comentario}/adjuntos/${file.id_adjunto}/acceso`}))}));return res.json({ok:true,source:'lab-sqlite',comentarios:rows,data:rows,pagination:{page:1,page_size:rows.length||1,total:rows.length,total_pages:1}});});
    router.post('/api/ventas/redes/:id/comentarios',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_COMENTARIOS.AGREGAR_COMENTARIO',SALES_GROUP),async(req,res)=>{const row=await services().sales.createNetworkComment(userId(req),req.params.id,req.body||{},actor(req),req.db);return res.status(201).json({ok:true,source:'lab-sqlite',comentario:row});});
    router.patch('/api/ventas/redes/:id/comentarios/:idComentario',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',comentario:services().sales.updateNetworkComment(userId(req),req.params.id,req.params.idComentario,req.body||{},actor(req),req.db)}));
    router.put('/api/ventas/redes/:id/comentarios/:idComentario',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',comentario:services().sales.updateNetworkComment(userId(req),req.params.id,req.params.idComentario,req.body||{},actor(req),req.db)}));
    router.delete('/api/ventas/redes/:id/comentarios/:idComentario',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),async(req,res)=>res.json({ok:true,source:'lab-sqlite',...(await services().sales.removeNetworkComment(userId(req),req.params.id,req.params.idComentario,req.db))}));
    router.post('/api/ventas/redes/:id/comentarios/:idComentario/adjuntos',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_COMENTARIOS.ADJUNTAR_ARCHIVO',SALES_GROUP),async(req,res)=>res.status(201).json({ok:true,source:'lab-sqlite',adjuntos:await services().sales.addNetworkCommentAttachments(userId(req),req.params.id,req.params.idComentario,req.body||{},actor(req),req.db)}));
    router.get('/api/ventas/redes/:id/comentarios/:idComentario/adjuntos/:idAdjunto/acceso',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_COMENTARIOS.VER',SALES_GROUP),async(req,res)=>{const data=await services().sales.networkAttachmentAccess(userId(req),req.params.id,req.params.idComentario,req.params.idAdjunto,req.db);return res.json({ok:true,source:'lab-sqlite',data,access_url:data.url||null,url:data.url||null});});
    router.delete('/api/ventas/redes/:id/comentarios/:idComentario/adjuntos/:idAdjunto',requireAuth,gate(['VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_COMENTARIOS.ADJUNTAR_ARCHIVO','VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR'],SALES_GROUP),async(req,res)=>res.json({ok:true,source:'lab-sqlite',...(await services().sales.removeNetworkAttachment(userId(req),req.params.id,req.params.idComentario,req.params.idAdjunto,req.db))}));
    router.patch('/api/ventas/redes/:id/estatus',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_DETALLE.CAMBIAR_ESTADO',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',registro:services().sales.updateNetworkStatus(userId(req),req.params.id,req.body||{},actor(req),req.db)}));
    router.patch('/api/ventas/redes/:id/asignacion',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.ASIGNAR_RESPONSABLES',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',registro:services().sales.updateNetworkAssignment(userId(req),req.params.id,req.body||{},actor(req),req.db)}));
    router.patch('/api/ventas/redes/:id/cotizacion',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_RELACION_COTIZACION.GESTIONAR_RELACION_COTIZACION',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',registro:services().sales.updateNetworkQuotation(userId(req),req.params.id,req.body||{},actor(req),req.db)}));
    router.get('/api/ventas/redes/:id',requireAuth,gate(NETWORK_DETAIL,SALES_GROUP),(req,res)=>{const row=services().sales.getNetwork(userId(req),req.params.id,req.db);row.archivos=(row.archivos||[]).map(file=>({...file,access_endpoint:`/api/ventas/redes/${req.params.id}/archivos/${file.id_archivo}/acceso`}));return res.json({ok:true,source:'lab-sqlite',registro:row,puede_asignar:redesCanAssign(req),visibilidad:services().sales.coreScope(userId(req),req.db)});});
    router.put('/api/ventas/redes/:id',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),(req,res)=>{const current=services().sales.getNetwork(userId(req),req.params.id,req.db),next=maybeAssigned(req.body?.id_usuario_asignado);if(next&&Number(current.id_usuario_asignado)!==next&&!has(req,'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.ASIGNAR_RESPONSABLES'))return res.status(403).json({ok:false,code:'LAB_FUNCTIONAL_PERMISSION_DENIED',message:'No tienes permiso para cambiar responsables en Redes.'});return res.json({ok:true,source:'lab-sqlite',registro:services().sales.updateNetwork(userId(req),req.params.id,req.body||{},actor(req),req.db)});});
    router.patch('/api/ventas/redes/:id',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),(req,res)=>{const current=services().sales.getNetwork(userId(req),req.params.id,req.db),next=maybeAssigned(req.body?.id_usuario_asignado);if(next&&Number(current.id_usuario_asignado)!==next&&!has(req,'VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.ASIGNAR_RESPONSABLES'))return res.status(403).json({ok:false,code:'LAB_FUNCTIONAL_PERMISSION_DENIED',message:'No tienes permiso para cambiar responsables en Redes.'});return res.json({ok:true,source:'lab-sqlite',registro:services().sales.updateNetwork(userId(req),req.params.id,req.body||{},actor(req),req.db)});});
    router.delete('/api/ventas/redes/:id',requireAuth,gate('VENTAS_ASIGNACION_REDES_TABLA_REGISTROS_EDITAR.EDITAR',SALES_GROUP),(req,res)=>res.json({ok:true,source:'lab-sqlite',...services().sales.removeNetwork(userId(req),req.params.id,actor(req),req.db)}));

    // Cobranza UNITED.
    router.post('/api/cobranza-uni/sync',requireAuth,local501);
    router.get('/api/cobranza-uni/gestion-credito',requireAuth,gate('COBRANZA_UNI_ESTADOS_CUENTA_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.listCredit(userId(req),req.query,req.db)));
    router.get('/api/cobranza-uni/gestion-credito/:id/detalle',requireAuth,gate('COBRANZA_UNI_ESTADOS_CUENTA_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.creditDetail(userId(req),req.params.id,req.db)));
    router.get('/api/cobranza-uni/venta-adicional',requireAuth,gate('COBRANZA_UNI_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.listAdditionalSales(userId(req),req.query,req.db)));
    router.get('/api/cobranza-uni/venta-adicional/:id/detalle',requireAuth,gate('COBRANZA_UNI_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.additionalSaleDetail(userId(req),req.params.id,req.db)));
    router.post('/api/cobranza-uni/detalle-mp-2026/sync',requireAuth,local501);
    router.get('/api/cobranza-uni/detalle-mp-2026',requireAuth,gate('COBRANZA_UNI_MANTENIMIENTO_PREVENTIVO_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.listPreventive(userId(req),req.query,req.db)));
    router.get('/api/cobranza-uni/detalle-mp-2026/:id',requireAuth,gate('COBRANZA_UNI_MANTENIMIENTO_PREVENTIVO_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',UNI_GROUP),(req,res)=>res.json(services().uni.preventiveDetail(userId(req),req.params.id,req.db)));

    // Cobranza CORELLIAN.
    router.post('/api/cobranza-cor/carga/indice',requireAuth,local501);router.post('/api/cobranza-cor/carga/fuente',requireAuth,local501);router.post('/api/cobranza-cor/carga/aditivas',requireAuth,local501);
    router.get('/api/cobranza-cor/estados-cuenta',requireAuth,gate('COBRANZA_ESTADOS_CUENTA_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.json(services().cor.listStatements(userId(req),req.query,req.db)));
    router.get('/api/cobranza-cor/estados-cuenta/:idIndiceCor',requireAuth,gate('COBRANZA_ESTADOS_CUENTA_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.json(services().cor.statementDetail(userId(req),req.params.idIndiceCor,req.db)));
    router.get('/api/cobranza-cor/aditivas',requireAuth,gate('COBRANZA_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.json(services().cor.listAdditions(userId(req),req.query,req.db)));
    router.post('/api/cobranza-cor/aditivas',requireAuth,gate('COBRANZA_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.status(201).json(services().cor.createAddition(userId(req),req.body||{},actor(req),req.db)));
    router.get('/api/cobranza-cor/aditivas/:idAditivaCor',requireAuth,gate('COBRANZA_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.json(services().cor.getAddition(userId(req),req.params.idAditivaCor,req.db)));
    router.put('/api/cobranza-cor/aditivas/:idAditivaCor',requireAuth,gate('COBRANZA_ADITIVAS_ACCESO_VISUAL_MODULO.ACCESO_VISUAL',COR_GROUP),(req,res)=>res.json(services().cor.updateAddition(userId(req),req.params.idAditivaCor,req.body||{},actor(req),req.db)));
    router.get('/api/cobranza-cor/adeudos-contractuales',requireAuth,(req,res)=>res.json(services().cor.contractualDebts(userId(req),req.query,req.db)));

    router.get('/api/__lab/sales-collections-status',requireAuth,(req,res)=>res.json({ok:true,source:'lab-sqlite',data:{version:'FASE_8_LAB_DGB_VENTAS_COBRANZA_V002',ventas_clientes:Number(req.db.scalar('SELECT COUNT(*) FROM ventas_clientes WHERE activo=1')||0),ventas_cotizaciones:Number(req.db.scalar('SELECT COUNT(*) FROM ventas_cotizaciones_cor WHERE activo=1')||0),ventas_prospecciones:Number(req.db.scalar('SELECT COUNT(*) FROM ventas_prospecciones WHERE activo=1')||0),ventas_redes:Number(req.db.scalar('SELECT COUNT(*) FROM ventas_redes WHERE activo=1')||0),cobranza_cor:Number(req.db.scalar('SELECT COUNT(*) FROM cobranza_indice_cor WHERE activo=1')||0),cobranza_uni:Number(req.db.scalar('SELECT COUNT(*) FROM gestion_credito')||0),productionConnectionsAllowed:false}}));
    return router;
  }

  return Object.freeze({register,SALES_GROUP,COR_GROUP,UNI_GROUP,QUOTE_DETAIL,CLIENT_DETAIL,PROSPECT_DETAIL,NETWORK_DETAIL,DASH_COMMERCIAL,DASH_OPERATIONAL});
});
