#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
function adapter(SQL){const raw=new SQL.Database();raw.exec('PRAGMA foreign_keys=ON');function query(sql,p){const st=raw.prepare(sql);try{if(p!==undefined)st.bind(p);const a=[];while(st.step())a.push(st.getAsObject());return a;}finally{st.free();}}function scalar(sql,p){const r=query(sql,p);return r.length?r[0][Object.keys(r[0])[0]]:null;}function run(sql,p){p===undefined?raw.run(sql):raw.run(sql,p);return{changes:Number(scalar('SELECT changes()')||0),lastInsertRowId:Number(scalar('SELECT last_insert_rowid()')||0)};}return{raw,query,scalar,run,exec:s=>raw.exec(s)};}
(async()=>{const init=require(path.join(ROOT,'lab/vendor/sql.js/1.14.2/sql-wasm.js'));const SQL=await init({locateFile:()=>path.join(ROOT,'lab/vendor/sql.js/1.14.2/sql-wasm.wasm')});const db=adapter(SQL);global.ManttoLabDB=db;for(const f of ['lab/database/schema.sql','lab/database/seed.sql','lab/database/migrations/004_permissions_catalog.sql','lab/database/migrations/005_shared_services.sql','lab/database/migrations/006_home_services.sql','lab/database/migrations/007_operation_portfolio.sql','lab/database/migrations/008_sales_collections.sql','lab/database/migrations/009_installations_logistics_warehouse.sql'])db.exec(read(f));
 require(path.join(ROOT,'lab/backend/services/lab-scope.service.js'));
 const blobs=new Map();global.ManttoLabBlobStore={isFileLike:f=>Boolean(f&&typeof f.arrayBuffer==='function'),put:async f=>{const key='p9-'+(blobs.size+1);blobs.set(key,f);return{key,name:f.name||'lab.txt',type:f.type||'text/plain',size:Number(f.size||1)};},accessUrl:async k=>blobs.has(k)?{access_url:'blob:'+k,nombre_archivo:blobs.get(k).name||'lab.txt',mime_type:blobs.get(k).type||'text/plain',tamano_bytes:Number(blobs.get(k).size||1)}:null,remove:async k=>blobs.delete(k)};
 require(path.join(ROOT,'lab/backend/services/lab-installations.service.js'));require(path.join(ROOT,'lab/backend/services/lab-logistics.service.js'));require(path.join(ROOT,'lab/backend/services/lab-warehouse.service.js'));
 const ins=global.ManttoLabInstallationsService,log=global.ManttoLabLogisticsService,wh=global.ManttoLabWarehouseService,actor=db.query('SELECT * FROM usuarios WHERE id_SB=910006')[0];
 const projects=ins.listProjects(910006,{},db);assert(projects.total>=15);const p=projects.proyectos[0];assert(p&&p.id_proyecto);const det=ins.detail(910006,p.id_proyecto,db);assert(det.proyecto);const folder=ins.ensureFolder(910006,p.id_proyecto,{},actor,db);assert(folder&&folder.id_carpeta);
 const fake={name:'lab-install.txt',type:'text/plain',size:4,arrayBuffer:async()=>new Uint8Array([1,2,3,4]).buffer};const doc=await ins.addDocument(910006,p.id_proyecto,{file:fake},actor,db);assert(doc.id_documento>0);const acc=await ins.docAccess(910006,p.id_proyecto,doc.id_documento,db);assert(String(acc.access_url).startsWith('blob:'));
 const before=log.list(910006,{},db).total;assert(before>=10);const created=log.create(910006,{proyecto:'LAB F9 LOGISTICA',ppns:'LAB-F9-PPNS',estatus_logistica:'EN PROCESO'},actor,db);assert(created.id_produccion>0);const updated=log.update(910006,created.id_produccion,{comentario:'QA F9'},actor,db);assert.equal(updated.comentario,'QA F9');const lf=await log.addFile(910006,created.id_produccion,{file:fake,tipo_archivo:'GM',numero_archivo:1},actor,db);assert(lf.id_archivo>0);assert((await log.fileAccess(910006,created.id_produccion,lf.id_archivo,db)).access_url);
 const inv=wh.inventory({},db);assert(inv.total>0);const dash=wh.dashboard(db);assert(dash.kpis.articulos>0);const sample=inv.data[0];const ex=wh.stockException({empresa:sample.empresa,codigo:sample.codigo,articulo:sample.articulo,motivo:'QA F9'},actor,db);assert(ex.id_excepcion>0);const aud=wh.createAudit({empresa:sample.empresa,almacen:sample.almacen},actor,db);assert(aud.registros>0);const first=aud.data[0];const au=wh.updateAudit(first.id_auditoria,{existencia_fisica:Number(first.existencia_esperada),observaciones:'QA F9'},actor,db);assert.equal(au.estatus,'EN_PROCESO');
 assert.equal(Number(db.scalar('PRAGMA user_version')),9);assert.equal(Number(db.scalar('SELECT COUNT(*) FROM pragma_foreign_key_check')),0);console.log('FASE 9 runtime services: OK');console.log('installations',projects.total);console.log('logistics_before',before);console.log('warehouse_inventory',inv.total);console.log('audit_rows',aud.registros);
})().catch(e=>{console.error(e);process.exit(1);});
