(function initManttoLabTicketsService(root,factory){
  const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ManttoLabTicketsService=api;
})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabTicketsService(root){
  'use strict';
  function txt(v){return String(v==null?'':v).trim();}
  function upper(v){return txt(v).toUpperCase();}
  function positive(v,fallback,min,max){const n=parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
  function visible(userId,db){return root.ManttoLabOperationService.visibleTickets(userId,db);}
  function find(userId,ref,db){const needle=txt(ref);return visible(userId,db).find(r=>txt(r.ticket)===needle||txt(r.id)===needle||txt(r.id_interno)===needle||txt(r.folio)===needle)||null;}
  function list(userId,q,db){const query=q||{},limit=positive(query.limit||query.page_size,20000,1,50000),page=positive(query.page,1,1,100000),zone=upper(query.zona),project=upper(query.proyecto),equipment=upper(query.equipo||query.codigo_equipo),status=upper(query.estado||query.estado_ticket),search=upper(query.search||query.buscar);let rows=visible(userId,db).filter(r=>(!zone||upper(r.zona_oficial).includes(zone))&&(!project||upper(r.proyecto).includes(project))&&(!equipment||upper(r.codigo_equipo).includes(equipment))&&(!status||upper(r.estado_ticket).includes(status))&&(!search||upper([r.ticket,r.proyecto,r.codigo_equipo,r.descripcion,r.causa,r.responsabilidad].join(' ')).includes(search)));const total=rows.length,start=(page-1)*limit;rows=rows.slice(start,start+limit);return{ok:true,source:'lab-sqlite',data:rows,pagination:{page,page_size:limit,total}};}
  function comments(ticketId,db){return(db||root.ManttoLabDB).query(`SELECT c.*,u.nombre,u.iniciales,u.correo FROM ticket_comentarios c LEFT JOIN usuarios u ON u.id_SB=c.id_usuario WHERE c.id_ticket=? AND c.activo=1 ORDER BY c.fecha_creacion ASC,c.id_comentario ASC`,[Number(ticketId)]);}
  function validations(ticketId,db){return(db||root.ManttoLabDB).query(`SELECT v.*,u.nombre,u.iniciales,u.correo FROM ticket_validaciones v LEFT JOIN usuarios u ON u.id_SB=v.id_usuario WHERE v.id_ticket=? ORDER BY v.fecha_creacion ASC,v.id_validacion ASC`,[Number(ticketId)]);}
  function detail(userId,ref,db){const row=find(userId,ref,db);if(!row)return null;return{ticket:row,comentarios:comments(row.id,db),validaciones:validations(row.id,db),interacciones:[...comments(row.id,db).map(x=>({tipo:'COMENTARIO',fecha:x.fecha_creacion,...x})),...validations(row.id,db).map(x=>({tipo:'VALIDACION',fecha:x.fecha_creacion,...x}))].sort((a,b)=>txt(a.fecha).localeCompare(txt(b.fecha)))};}
  async function saveVobo(userId,ref,body,actor,db){const database=db||root.ManttoLabDB,row=find(userId,ref,database);if(!row){const e=new Error('Ticket no encontrado o fuera de alcance.');e.status=404;e.code='LAB_TICKET_NOT_FOUND';throw e;}const next=txt(body?.vobo_estado||'Pendiente'),comment=txt(body?.vobo_comentario),before=txt(row.vobo_estado||'PENDIENTE');database.run(`INSERT INTO ticket_validaciones(id_ticket,id_usuario,estado_anterior,estado_nuevo,comentario,ip_origen) VALUES(?,?,?,?,?,?)`,[Number(row.id),Number(actor?.id_SB||actor?.id||userId),before,next,comment||null,'LAB']);database.run(`UPDATE tickets SET vobo_estado=?,vobo_comentario=?,vobo_por_id=?,vobo_por_nombre=?,vobo_en=CURRENT_TIMESTAMP,actualizado_en=CURRENT_TIMESTAMP WHERE id=?`,[next,comment||null,Number(actor?.id_SB||actor?.id||userId),txt(actor?.nombre||actor?.iniciales||'Usuario LAB'),Number(row.id)]);await root.ManttoLabInteractionsService?.record?.({id_usuario:Number(actor?.id_SB||actor?.id||userId),tipo_interaccion:next.toUpperCase()==='PENDIENTE'?'ACTUALIZAR':'VALIDAR',modulo:'tickets',entidad:'ticket',id_referencia:row.ticket,titulo:`Actualizaste Ticket #${row.ticket}`,descripcion:`Vo.Bo. ${next}`,ruta_destino:'detalle',payload_json:{type:'ticket',id:row.ticket},detalle_json:{contexto:{ticket:row.ticket,proyecto:row.proyecto,equipo:row.codigo_equipo}}},database);return{ticket:row.ticket,vobo_estado:next,vobo_comentario:comment||null};}
  async function addComment(userId,ref,body,actor,db){const database=db||root.ManttoLabDB,row=find(userId,ref,database);if(!row){const e=new Error('Ticket no encontrado o fuera de alcance.');e.status=404;throw e;}const comment=txt(body?.comentario);if(!comment){const e=new Error('El comentario es obligatorio.');e.status=400;throw e;}const result=database.run(`INSERT INTO ticket_comentarios(id_ticket,id_usuario,comentario,activo) VALUES(?,?,?,1)`,[Number(row.id),Number(actor?.id_SB||actor?.id||userId),comment]);await root.ManttoLabInteractionsService?.record?.({id_usuario:Number(actor?.id_SB||actor?.id||userId),tipo_interaccion:'COMENTAR',modulo:'tickets',entidad:'ticket',id_referencia:row.ticket,titulo:`Comentaste en Ticket #${row.ticket}`,descripcion:comment.slice(0,500),ruta_destino:'detalle',payload_json:{type:'ticket',id:row.ticket},detalle_json:{contexto:{ticket:row.ticket,proyecto:row.proyecto,equipo:row.codigo_equipo}}},database);return{id_comentario:Number(result.lastInsertRowId),comentario:comment};}
  return Object.freeze({list,find,detail,saveVobo,addComment,comments,validations});
});
