(function initManttoLabSalesService(root, factory) {
  const api = factory(root);
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.ManttoLabSalesService = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createManttoLabSalesService(root) {
  'use strict';

  const QUOTE_STATUSES = Object.freeze([
    'Contacto','En Cotizacion','Sin Respuesta','Seguimiento con Probabilidad',
    'En Espera de Definicion','Pre Asignado','Asignado','En Contrato',
    'Vendido','Perdido','Siguiente Año','Borrar'
  ]);
  const ACTIVE_QUOTE_STATUSES = Object.freeze([
    'Contacto','En Cotizacion','Sin Respuesta','Seguimiento con Probabilidad',
    'En Espera de Definicion','Pre Asignado','Asignado','En Contrato'
  ]);
  const EQUIPMENT_TYPES = Object.freeze(['Elevador','Montacargas','Escalera','Rampa','Plataformas/Otros']);

  function dbOr(candidate) {
    const db = candidate || root?.ManttoLabDB;
    if (!db || typeof db.query !== 'function' || typeof db.scalar !== 'function' || typeof db.run !== 'function') throw new Error('MANTTO_LAB_DB_REQUIRED');
    return db;
  }
  function httpError(status, message, code) { const error=new Error(message);error.status=status;error.statusCode=status;error.code=code||'LAB_SALES_ERROR';return error; }
  function id(value, field='id') { const n=Number(value);if(!Number.isInteger(n)||n<=0)throw httpError(400,`${field} debe ser un entero positivo.`,'LAB_INVALID_ID');return n; }
  function maybeId(value) { const n=Number(value);return Number.isInteger(n)&&n>0?n:null; }
  function text(value, max=500, fallback=null) { const v=value==null?'':String(value).trim();return v?v.slice(0,max):fallback; }
  function bool(value) { return value===true||value===1||value==='1'||String(value||'').toLowerCase()==='true'; }
  function upper(value) { return String(value||'').trim().toUpperCase(); }
  function now() { return new Date().toISOString().replace('T',' ').slice(0,19); }
  function pageOf(query, defaultSize=25, max=100) { const page=Math.max(1,parseInt(query?.page??query?.pagina??'1',10)||1);const size=Math.min(max,Math.max(1,parseInt(query?.page_size??query?.tamano_pagina??defaultSize,10)||defaultSize));return{page,size,offset:(page-1)*size}; }
  function values(body) { return body&&typeof body==='object'?body:{}; }
  function actorId(actor) { return id(actor?.id_SB||actor?.id||actor?.user_id,'usuario autenticado'); }
  function uniqueIds(items) { return [...new Set((items||[]).map(Number).filter(v=>Number.isInteger(v)&&v>0))]; }
  function sqlIn(ids) { return ids.map(()=>'?').join(','); }
  function parseJson(value) { if(value==null||value==='')return null;if(typeof value==='object')return value;try{return JSON.parse(String(value));}catch(_e){return null;} }
  function fileLike(value) { return Boolean(value&&typeof value==='object'&&Number.isFinite(Number(value.size))&&typeof value.arrayBuffer==='function'); }
  function collectFiles(body) { const files=[];Object.values(values(body)).forEach(v=>{if(Array.isArray(v))v.forEach(x=>{if(fileLike(x))files.push(x);});else if(fileLike(v))files.push(v);});return files; }

  function coreScope(userId, candidateDb) {
    const service=root?.ManttoLabScopeService;if(!service?.resolveCorellian)throw new Error('MANTTO_LAB_SCOPE_SERVICE_REQUIRED');
    return service.resolveCorellian(Number(userId),dbOr(candidateDb));
  }
  function visibleUserIds(userId, candidateDb) {
    const scope=coreScope(userId,candidateDb);return scope.llave_maestra?null:uniqueIds(scope.usuarios_visibles||[Number(userId)]);
  }
  function visibleUser(userId, targetId, candidateDb) { const ids=visibleUserIds(userId,candidateDb);return ids===null||ids.includes(Number(targetId)); }
  function quoteScopeSql(userId, alias, candidateDb) {
    const ids=visibleUserIds(userId,candidateDb);const a=alias?`${alias}.`:'';
    if(ids===null)return{sql:'1=1',params:[]};if(!ids.length)return{sql:'1=0',params:[]};const ph=sqlIn(ids);
    return{sql:`(${a}id_asesor IN (${ph}) OR ${a}id_admin IN (${ph}))`,params:[...ids,...ids]};
  }
  function prospectScopeSql(userId, alias, candidateDb) {
    const ids=visibleUserIds(userId,candidateDb);const a=alias?`${alias}.`:'';
    if(ids===null)return{sql:'1=1',params:[]};if(!ids.length)return{sql:'1=0',params:[]};return{sql:`${a}id_usuario IN (${sqlIn(ids)})`,params:ids};
  }
  function networkScopeSql(userId, alias, candidateDb) {
    const ids=visibleUserIds(userId,candidateDb);const a=alias?`${alias}.`:'';
    if(ids===null)return{sql:'1=1',params:[]};if(!ids.length)return{sql:'1=0',params:[]};
    return{sql:`${a}id_usuario_asignado IN (${sqlIn(ids)})`,params:ids};
  }
  function clientScopeSql(userId, alias, candidateDb) {
    const ids=visibleUserIds(userId,candidateDb);const a=alias?`${alias}.`:'';
    if(ids===null)return{sql:'1=1',params:[]};if(!ids.length)return{sql:'1=0',params:[]};
    return{sql:`EXISTS (SELECT 1 FROM usuarios vu WHERE vu.estado=1 AND vu.id_SB IN (${sqlIn(ids)}) AND UPPER(TRIM(COALESCE(vu.iniciales,'')))=UPPER(TRIM(COALESCE(${a}iniciales,''))))`,params:ids};
  }

  function userPublic(db, userId) { return db.query('SELECT id_SB,nombre,iniciales,correo,empresa,puesto,rol_id FROM usuarios WHERE id_SB=? AND estado=1 LIMIT 1',[Number(userId)])[0]||null; }
  function visibleCommercialUsers(userId,candidateDb) {
    const db=dbOr(candidateDb), ids=visibleUserIds(userId,db);let rows;
    if(ids===null) rows=db.query(`SELECT id_SB,nombre,iniciales,correo,empresa,puesto,rol_id FROM usuarios WHERE estado=1 AND id_SB IN (SELECT DISTINCT id_asesor FROM ventas_cotizaciones_cor WHERE id_asesor IS NOT NULL UNION SELECT DISTINCT id_admin FROM ventas_cotizaciones_cor WHERE id_admin IS NOT NULL) ORDER BY nombre`);
    else if(!ids.length) rows=[];
    else rows=db.query(`SELECT id_SB,nombre,iniciales,correo,empresa,puesto,rol_id FROM usuarios WHERE estado=1 AND id_SB IN (${sqlIn(ids)}) ORDER BY nombre`,ids);
    return rows.map(row=>({...row,id_usuario:Number(row.id_SB),tipo_perfil:row.puesto||row.area||null}));
  }

  function catalogPeople(candidateDb) {
    const db=dbOr(candidateDb);
    const asesores=db.query(`SELECT DISTINCT u.id_SB,u.nombre,u.iniciales,u.correo,u.empresa,u.puesto FROM usuarios u WHERE u.estado=1 AND u.id_SB IN (SELECT id_asesor FROM ventas_cotizaciones_cor WHERE id_asesor IS NOT NULL) ORDER BY u.nombre`);
    const administrativos=db.query(`SELECT DISTINCT u.id_SB,u.nombre,u.iniciales,u.correo,u.empresa,u.puesto FROM usuarios u WHERE u.estado=1 AND u.id_SB IN (SELECT id_admin FROM ventas_cotizaciones_cor WHERE id_admin IS NOT NULL UNION SELECT id_admin FROM usuarios_rel_admin) ORDER BY u.nombre`);
    return {asesores,administrativos};
  }

  function clientVisible(userId, clientId, candidateDb) { const db=dbOr(candidateDb),scope=clientScopeSql(userId,'c',db);return Boolean(db.scalar(`SELECT 1 FROM ventas_clientes c WHERE c.id_cliente=? AND c.activo=1 AND ${scope.sql} LIMIT 1`,[Number(clientId),...scope.params])); }
  function clientCatalogs(userId,candidateDb) {
    const db=dbOr(candidateDb),scope=clientScopeSql(userId,'c',db), people=catalogPeople(db);
    const rows=db.query(`SELECT c.tipo_cliente,c.estatus_cliente,c.estado,c.ciudad FROM ventas_clientes c WHERE c.activo=1 AND ${scope.sql}`,[...scope.params]);
    const tipos=[...new Set(rows.map(r=>r.tipo_cliente).filter(Boolean))].sort(),estatus=[...new Set(rows.map(r=>r.estatus_cliente).filter(Boolean))].sort(),estados=[...new Set(rows.map(r=>r.estado).filter(Boolean))].sort(),ciudades=[...new Set(rows.map(r=>r.ciudad).filter(Boolean))].sort(),iniciales=[...new Set(people.asesores.map(r=>r.iniciales).filter(Boolean))].sort();return {asesores:people.asesores,administrativos:people.administrativos,tipo_cliente:tipos,tipos_cliente:tipos,estatus_cliente:estatus,estado:estados,estados,ciudades,iniciales};
  }
  function listClients(userId,query,candidateDb) {
    const db=dbOr(candidateDb),scope=clientScopeSql(userId,'c',db),p=pageOf(query,30,100),clauses=['c.activo=1',scope.sql],params=[...scope.params];
    const search=text(query?.search??query?.buscar,120);if(search){clauses.push(`(c.nombre_empresa LIKE ? OR c.razon_social LIKE ? OR c.nombre_contacto LIKE ? OR c.email LIKE ? OR c.ciudad LIKE ? OR c.estado LIKE ?)`);params.push(...Array(6).fill(`%${search}%`));}
    if(query?.estatus_cliente){clauses.push('c.estatus_cliente=?');params.push(String(query.estatus_cliente));}if(query?.tipo_cliente){clauses.push('c.tipo_cliente=?');params.push(String(query.tipo_cliente));}if(query?.estado){clauses.push('c.estado=?');params.push(String(query.estado));}if(query?.iniciales){clauses.push("UPPER(TRIM(COALESCE(c.iniciales,'')))=UPPER(TRIM(?))");params.push(String(query.iniciales));}
    const where=clauses.join(' AND '),total=Number(db.scalar(`SELECT COUNT(*) FROM ventas_clientes c WHERE ${where}`,params)||0);
    const rows=db.query(`SELECT c.*,(SELECT COUNT(*) FROM ventas_cotizaciones_cor q WHERE q.id_cliente=c.id_cliente AND q.activo=1) AS cotizaciones,(SELECT COUNT(*) FROM ventas_cotizaciones_cor q WHERE q.id_cliente=c.id_cliente AND q.activo=1 AND UPPER(TRIM(COALESCE(q.estatus_proyecto,''))) NOT IN ('VENDIDO','PERDIDO')) AS en_proceso,(SELECT COUNT(*) FROM ventas_cotizaciones_cor q WHERE q.id_cliente=c.id_cliente AND q.activo=1 AND UPPER(TRIM(COALESCE(q.estatus_proyecto,'')))='VENDIDO') AS vendidas,(SELECT COUNT(*) FROM ventas_cotizaciones_cor q WHERE q.id_cliente=c.id_cliente AND q.activo=1 AND UPPER(TRIM(COALESCE(q.estatus_proyecto,'')))='PERDIDO') AS perdidas,(SELECT COUNT(*) FROM ventas_clientes_contactos cc WHERE cc.id_cliente=c.id_cliente AND cc.activo=1) AS contactos FROM ventas_clientes c WHERE ${where} ORDER BY c.nombre_empresa LIMIT ? OFFSET ?`,[...params,p.size,p.offset]);
    const totalPages=Math.max(1,total?Math.ceil(total/p.size):1);return{clientes:rows,data:rows,paginacion:{pagina:p.page,tamano_pagina:p.size,total_registros:total,total,total_paginas:total?Math.ceil(total/p.size):0},pagination:{page:p.page,page_size:p.size,total,total_pages:totalPages},alcance:coreScope(userId,db)};
  }
  function getClient(userId,clientId,candidateDb) {
    const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),scope=clientScopeSql(userId,'c',db);const row=db.query(`SELECT c.* FROM ventas_clientes c WHERE c.id_cliente=? AND c.activo=1 AND ${scope.sql} LIMIT 1`,[cid,...scope.params])[0];if(!row)throw httpError(404,'Cliente no encontrado o fuera de tu alcance.','LAB_SALES_CLIENT_NOT_FOUND');
    const contacts=db.query('SELECT * FROM ventas_clientes_contactos WHERE id_cliente=? AND activo=1 ORDER BY contacto_principal DESC,nombre_contacto',[cid]);return{...row,contactos:contacts};
  }
  function validateClientBody(body) { const b=values(body);const nombre=text(b.nombre_empresa,200);if(!nombre)throw httpError(400,'nombre_empresa es obligatorio.','LAB_SALES_CLIENT_NAME_REQUIRED');return{nombre_empresa:nombre,razon_social:text(b.razon_social,220),ciudad:text(b.ciudad,120),estado:text(b.estado,120),ubicacion:text(b.ubicacion,300),nombre_contacto:text(b.nombre_contacto,180),puesto_contacto:text(b.puesto_contacto,150),email:text(b.email,200),telefono:text(b.telefono,80),tipo_cliente:text(b.tipo_cliente,80),estatus_cliente:text(b.estatus_cliente,80,'ACTIVO'),proyecto_vendido:text(b.proyecto_vendido,220),iniciales:text(b.iniciales,20),visualiza:text(b.visualiza,80),comentarios:text(b.comentarios,3000)}; }
  function createClient(body,actor,candidateDb) { const db=dbOr(candidateDb),uid=actorId(actor),b=validateClientBody(body);const duplicate=Number(db.scalar('SELECT COUNT(*) FROM ventas_clientes WHERE activo=1 AND UPPER(TRIM(nombre_empresa))=UPPER(TRIM(?))',[b.nombre_empresa])||0);if(duplicate)throw httpError(409,'Ya existe un cliente activo con ese nombre.','LAB_SALES_CLIENT_DUPLICATE');const r=db.run(`INSERT INTO ventas_clientes(nombre_empresa,razon_social,ciudad,estado,ubicacion,nombre_contacto,puesto_contacto,email,telefono,tipo_cliente,estatus_cliente,proyecto_vendido,iniciales,visualiza,comentarios,activo,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[b.nombre_empresa,b.razon_social,b.ciudad,b.estado,b.ubicacion,b.nombre_contacto,b.puesto_contacto,b.email,b.telefono,b.tipo_cliente,b.estatus_cliente,b.proyecto_vendido,b.iniciales,b.visualiza,b.comentarios,1,uid,uid]);return getClient(uid,r.lastInsertRowId,db); }
  function updateClient(userId,clientId,body,actor,candidateDb) { const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),uid=actorId(actor);getClient(userId,cid,db);const existing=db.query('SELECT * FROM ventas_clientes WHERE id_cliente=?',[cid])[0],b={...existing,...values(body)};const clean=validateClientBody(b);db.run(`UPDATE ventas_clientes SET nombre_empresa=?,razon_social=?,ciudad=?,estado=?,ubicacion=?,nombre_contacto=?,puesto_contacto=?,email=?,telefono=?,tipo_cliente=?,estatus_cliente=?,proyecto_vendido=?,iniciales=?,visualiza=?,comentarios=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cliente=?`,[clean.nombre_empresa,clean.razon_social,clean.ciudad,clean.estado,clean.ubicacion,clean.nombre_contacto,clean.puesto_contacto,clean.email,clean.telefono,clean.tipo_cliente,clean.estatus_cliente,clean.proyecto_vendido,clean.iniciales,clean.visualiza,clean.comentarios,uid,cid]);return getClient(userId,cid,db); }
  function removeClient(userId,clientId,actor,candidateDb) { const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),uid=actorId(actor);getClient(userId,cid,db);db.run('UPDATE ventas_clientes SET activo=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cliente=?',[uid,cid]);return{id_cliente:cid,activo:false}; }
  function listContacts(userId,clientId,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente');getClient(userId,cid,db);return db.query('SELECT * FROM ventas_clientes_contactos WHERE id_cliente=? AND activo=1 ORDER BY contacto_principal DESC,nombre_contacto',[cid]);}
  function createContact(userId,clientId,body,actor,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),uid=actorId(actor);getClient(userId,cid,db);const b=values(body),name=text(b.nombre_contacto,180);if(!name)throw httpError(400,'nombre_contacto es obligatorio.');if(bool(b.contacto_principal))db.run('UPDATE ventas_clientes_contactos SET contacto_principal=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cliente=?',[uid,cid]);const r=db.run('INSERT INTO ventas_clientes_contactos(id_cliente,nombre_contacto,puesto_contacto,email,telefono,contacto_principal,activo,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)',[cid,name,text(b.puesto_contacto,150),text(b.email,200),text(b.telefono,80),bool(b.contacto_principal)?1:0,1,uid,uid]);return db.query('SELECT * FROM ventas_clientes_contactos WHERE id_contacto=?',[r.lastInsertRowId])[0];}
  function updateContact(userId,clientId,contactId,body,actor,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),contact=id(contactId,'id_contacto'),uid=actorId(actor);getClient(userId,cid,db);const old=db.query('SELECT * FROM ventas_clientes_contactos WHERE id_contacto=? AND id_cliente=? AND activo=1',[contact,cid])[0];if(!old)throw httpError(404,'Contacto no encontrado.');const b={...old,...values(body)},name=text(b.nombre_contacto,180);if(!name)throw httpError(400,'nombre_contacto es obligatorio.');if(bool(b.contacto_principal))db.run('UPDATE ventas_clientes_contactos SET contacto_principal=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cliente=?',[uid,cid]);db.run('UPDATE ventas_clientes_contactos SET nombre_contacto=?,puesto_contacto=?,email=?,telefono=?,contacto_principal=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_contacto=?',[name,text(b.puesto_contacto,150),text(b.email,200),text(b.telefono,80),bool(b.contacto_principal)?1:0,uid,contact]);return db.query('SELECT * FROM ventas_clientes_contactos WHERE id_contacto=?',[contact])[0];}
  function removeContact(userId,clientId,contactId,actor,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),contact=id(contactId,'id_contacto'),uid=actorId(actor);getClient(userId,cid,db);if(!db.scalar('SELECT 1 FROM ventas_clientes_contactos WHERE id_contacto=? AND id_cliente=? AND activo=1',[contact,cid]))throw httpError(404,'Contacto no encontrado.');db.run('UPDATE ventas_clientes_contactos SET activo=0,contacto_principal=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_contacto=?',[uid,contact]);return{id_contacto:contact,activo:false};}
  function setPrincipalContact(userId,clientId,contactId,actor,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),contact=id(contactId,'id_contacto'),uid=actorId(actor);getClient(userId,cid,db);if(!db.scalar('SELECT 1 FROM ventas_clientes_contactos WHERE id_contacto=? AND id_cliente=? AND activo=1',[contact,cid]))throw httpError(404,'Contacto no encontrado.');db.run('UPDATE ventas_clientes_contactos SET contacto_principal=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cliente=?',[uid,cid]);db.run('UPDATE ventas_clientes_contactos SET contacto_principal=1,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_contacto=?',[uid,contact]);return db.query('SELECT * FROM ventas_clientes_contactos WHERE id_contacto=?',[contact])[0];}

  function assertClientAndContact(userId,clientId,contactId,candidateDb){const db=dbOr(candidateDb),cid=id(clientId,'id_cliente'),coid=id(contactId,'id_contacto');if(!clientVisible(userId,cid,db))throw httpError(404,'Cliente no encontrado o fuera de tu alcance.','LAB_SALES_CLIENT_NOT_FOUND');const client=db.query('SELECT * FROM ventas_clientes WHERE id_cliente=? AND activo=1',[cid])[0],contact=db.query('SELECT * FROM ventas_clientes_contactos WHERE id_contacto=? AND id_cliente=? AND activo=1',[coid,cid])[0];if(!contact)throw httpError(404,'Contacto no encontrado para el cliente seleccionado.','LAB_SALES_CONTACT_NOT_FOUND');return{client,contact};}
  function quotationVisible(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=id(quoteId,'id_cotizacion'),scope=quoteScopeSql(userId,'q',db);return Boolean(db.scalar(`SELECT 1 FROM ventas_cotizaciones_cor q WHERE q.id_cotizacion=? AND q.activo=1 AND ${scope.sql} LIMIT 1`,[qid,...scope.params]));}
  function assertQuote(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=id(quoteId,'id_cotizacion');if(!quotationVisible(userId,qid,db))throw httpError(404,'Cotización no encontrada o fuera de tu alcance.','LAB_SALES_QUOTE_NOT_FOUND');return qid;}
  function interestMap(userId,quoteIds,candidateDb){const db=dbOr(candidateDb),uid=Number(userId),ids=uniqueIds(quoteIds);if(!ids.length)return new Set();const refs=ids.map(String),ph=sqlIn(refs);const rows=db.query(`SELECT ui.id_referencia,ui.tipo_interaccion FROM usuario_interacciones ui JOIN (SELECT id_referencia,MAX(id_interaccion) id_interaccion FROM usuario_interacciones WHERE id_usuario=? AND modulo='ventas-cotizaciones' AND entidad='cotizacion' AND tipo_interaccion IN ('PROYECTO_INTERES_ACTIVADO','PROYECTO_INTERES_DESACTIVADO') AND id_referencia IN (${ph}) GROUP BY id_referencia) x ON x.id_interaccion=ui.id_interaccion`,[uid,...refs]);return new Set(rows.filter(r=>r.tipo_interaccion==='PROYECTO_INTERES_ACTIVADO').map(r=>String(r.id_referencia)));}
  function quoteCatalogs(userId,candidateDb){const db=dbOr(candidateDb),scope=quoteScopeSql(userId,'q',db),people=catalogPeople(db),rows=db.query(`SELECT q.estado,q.zona,q.anio_actual FROM ventas_cotizaciones_cor q WHERE q.activo=1 AND ${scope.sql}`,[...scope.params]);const relations=db.query('SELECT ura.id_asesor,ura.id_admin,a.iniciales AS asesor,d.iniciales AS admin FROM usuarios_rel_admin ura LEFT JOIN usuarios a ON a.id_SB=ura.id_asesor LEFT JOIN usuarios d ON d.id_SB=ura.id_admin ORDER BY ura.id_asesor,ura.id_admin');return{asesores:people.asesores,administrativos:people.administrativos,usuarios_asesores:people.asesores,usuarios_administrativos:people.administrativos,estados:[...new Set(rows.map(r=>r.estado).filter(Boolean))].sort(),zonas:[...new Set(rows.map(r=>r.zona).filter(Boolean))].sort(),estado_zonas:[...new Map(rows.filter(r=>r.estado&&r.zona).map(r=>[`${r.estado}|${r.zona}`,{estado:r.estado,zona:r.zona}])).values()],anios:[...new Set(rows.map(r=>Number(r.anio_actual)).filter(Boolean))].sort((a,b)=>b-a),relaciones_admin:relations,estatus:[...QUOTE_STATUSES],tipos_equipo:[...EQUIPMENT_TYPES]};}
  function quoteWhere(userId,query,candidateDb){const db=dbOr(candidateDb),scope=quoteScopeSql(userId,'q',db),clauses=['q.activo=1',scope.sql],params=[...scope.params];const search=text(query?.search??query?.buscar,120);if(search){clauses.push('(q.nombre_proyecto LIKE ? OR q.cliente LIKE ? OR q.contacto LIKE ? OR q.asesor LIKE ? OR q.admin LIKE ? OR q.ciudad LIKE ? OR q.estado LIKE ? OR CAST(q.id_cotizacion AS TEXT) LIKE ?)');params.push(...Array(8).fill(`%${search}%`));}const year=String(query?.anio??'').trim();if(year&&year.toLowerCase()!=='todos'){clauses.push('COALESCE(q.anio_actual,CAST(substr(q.fecha_cotizacion,1,4) AS INTEGER))=?');params.push(Number(year));}if(query?.estatus_proyecto){clauses.push('q.estatus_proyecto=?');params.push(String(query.estatus_proyecto));}if(maybeId(query?.id_asesor)){clauses.push('q.id_asesor=?');params.push(Number(query.id_asesor));}if(maybeId(query?.id_admin)){clauses.push('q.id_admin=?');params.push(Number(query.id_admin));}if(query?.estado){clauses.push('q.estado=?');params.push(String(query.estado));}if(query?.zona){clauses.push('q.zona=?');params.push(String(query.zona));}return{sql:clauses.join(' AND '),params};}
  function listQuotes(userId,query,candidateDb){const db=dbOr(candidateDb),p=pageOf(query,25,100),where=quoteWhere(userId,query,db),total=Number(db.scalar(`SELECT COUNT(*) FROM ventas_cotizaciones_cor q WHERE ${where.sql}`,where.params)||0);const rows=db.query(`SELECT q.*,(SELECT COALESCE(SUM(e.cantidad),0) FROM ventas_cotizaciones_equipos_cor e WHERE e.id_cotizacion=q.id_cotizacion AND e.activo=1) AS equipos_detalle FROM ventas_cotizaciones_cor q WHERE ${where.sql} ORDER BY COALESCE(q.fecha_cotizacion,q.fecha_solicitud,q.created_at) DESC,q.id_cotizacion DESC LIMIT ? OFFSET ?`,[...where.params,p.size,p.offset]);const interests=interestMap(userId,rows.map(r=>r.id_cotizacion),db);const data=rows.map(r=>({...r,proyecto_interes:interests.has(String(r.id_cotizacion))}));return{cotizaciones:data,data,paginacion:{pagina:p.page,tamano_pagina:p.size,total_registros:total,total:total,total_paginas:total?Math.ceil(total/p.size):0},alcance:coreScope(userId,db)};}
  function getQuote(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),q=db.query('SELECT * FROM ventas_cotizaciones_cor WHERE id_cotizacion=?',[qid])[0];const equipment=db.query('SELECT * FROM ventas_cotizaciones_equipos_cor WHERE id_cotizacion=? AND activo=1 ORDER BY orden,id_cotizacion_equipo',[qid]);const comments=listQuoteComments(userId,qid,db);const files=listQuoteFiles(userId,qid,db);return{...q,equipos:equipment,comentarios:comments,archivos:files,proyecto_interes:interestMap(userId,[qid],db).has(String(qid))};}
  function kpisQuotes(userId,query,candidateDb){const db=dbOr(candidateDb),where=quoteWhere(userId,query,db),rows=db.query(`SELECT estatus_proyecto,numero_equipos FROM ventas_cotizaciones_cor q WHERE ${where.sql}`,where.params);const sum=filter=>rows.filter(filter).reduce((a,r)=>a+Number(r.numero_equipos||0),0),status=s=>upper(s.estatus_proyecto);return{kpis:{total_cotizaciones:rows.length,total:rows.length,embudo_activo:rows.filter(r=>ACTIVE_QUOTE_STATUSES.map(upper).includes(status(r))).length,vendidas:rows.filter(r=>status(r)==='VENDIDO').length,perdidas:rows.filter(r=>status(r)==='PERDIDO').length,total_equipos:sum(()=>true),equipos_vendidos:sum(r=>status(r)==='VENDIDO'),equipos_perdidos:sum(r=>status(r)==='PERDIDO')}};}
  function quoteByStatus(userId,statuses,query,candidateDb){const q={...query};delete q.estatus_proyecto;const list=listQuotes(userId,{...q,page:1,page_size:100},candidateDb).cotizaciones;const set=new Set(statuses.map(upper));return list.filter(r=>set.has(upper(r.estatus_proyecto)));}
  function quoteDashboardProjection(userId,query,candidateDb){return quoteByStatus(userId,ACTIVE_QUOTE_STATUSES,query,candidateDb);}
  function createQuote(body,actor,candidateDb){const db=dbOr(candidateDb),uid=actorId(actor),b=values(body),name=text(b.nombre_proyecto,220);if(!name)throw httpError(400,'nombre_proyecto es obligatorio.','LAB_SALES_QUOTE_REQUIRED');const related=assertClientAndContact(uid,b.id_cliente,b.id_contacto,db),client=text(b.cliente,220,related.client.nombre_empresa),contactName=text(b.contacto,180,related.contact.nombre_contacto);const initials=text(related.client.iniciales,30);const assignedByClient=initials?db.query('SELECT id_SB,iniciales FROM usuarios WHERE estado=1 AND UPPER(TRIM(iniciales))=UPPER(TRIM(?)) ORDER BY id_SB LIMIT 1',[initials])[0]:null;const advisor=maybeId(b.id_asesor)||maybeId(assignedByClient?.id_SB)||uid,admin=maybeId(b.id_admin);if(!visibleUser(uid,advisor,db)||admin&&!visibleUser(uid,admin,db))throw httpError(403,'La asignación está fuera de tu alcance comercial.','LAB_SALES_ASSIGNMENT_SCOPE');const status=QUOTE_STATUSES.includes(String(b.estatus_proyecto))?String(b.estatus_proyecto):'Contacto';const year=Number(b.anio_actual||String(b.fecha_cotizacion||b.fecha_solicitud||new Date().toISOString()).slice(0,4))||new Date().getFullYear();const r=db.run(`INSERT INTO ventas_cotizaciones_cor(nombre_proyecto,id_cliente,id_contacto,cliente,contacto,telefono,correo,ciudad,estado,tipo_proyecto,numero_equipos,tipo_equipos,informacion_envia,asesor,id_asesor,visualiza,anio_mes_cotizacion,mx,fecha_cotizacion,fecha_solicitud,zona,estatus_proyecto,razon_perdido,admin,id_admin,fecha_cambio_estatus,fecha_cierre,comentario,empresa_vs_perdido,id_equipo_vendido,anio_actual,activo,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[name,Number(related.client.id_cliente),Number(related.contact.id_contacto),client,contactName,text(b.telefono,80,related.contact.telefono),text(b.correo,200,related.contact.email),text(b.ciudad,120,related.client.ciudad),text(b.estado,120,related.client.estado),text(b.tipo_proyecto,120),Math.max(0,Number(b.numero_equipos||0)||0),text(b.tipo_equipos,200),text(b.informacion_envia,1000),text(b.asesor,30,assignedByClient?.iniciales||actor?.iniciales||null),advisor,text(b.visualiza,80,'LAB'),text(b.anio_mes_cotizacion,20),text(b.mx,30,'MXN'),text(b.fecha_cotizacion,30),text(b.fecha_solicitud,30),text(b.zona,80),status,text(b.razon_perdido,1000),text(b.admin,30),admin,now(),text(b.fecha_cierre,30),text(b.comentario,3000),text(b.empresa_vs_perdido,300),text(b.id_equipo_vendido,100),year,1,uid,uid]);const qid=Number(r.lastInsertRowId);replaceQuoteEquipment(qid,b.equipos||[],db);insertHistory(qid,null,status,uid,actor?.iniciales,'ALTA','estatus_proyecto',null,status,'Alta LAB',db);return getQuote(uid,qid,db);}
  function updateQuote(userId,quoteId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),old=db.query('SELECT * FROM ventas_cotizaciones_cor WHERE id_cotizacion=?',[qid])[0],b={...old,...values(body)};const name=text(b.nombre_proyecto,220),client=text(b.cliente,220);if(!name||!client)throw httpError(400,'nombre_proyecto y cliente son obligatorios.');const advisor=maybeId(b.id_asesor),admin=maybeId(b.id_admin);if(advisor&&!visibleUser(userId,advisor,db)||admin&&!visibleUser(userId,admin,db))throw httpError(403,'La asignación está fuera de tu alcance comercial.');db.run(`UPDATE ventas_cotizaciones_cor SET nombre_proyecto=?,id_cliente=?,id_contacto=?,cliente=?,contacto=?,telefono=?,correo=?,ciudad=?,estado=?,tipo_proyecto=?,numero_equipos=?,tipo_equipos=?,informacion_envia=?,asesor=?,id_asesor=?,visualiza=?,anio_mes_cotizacion=?,mx=?,fecha_cotizacion=?,fecha_solicitud=?,zona=?,estatus_proyecto=?,razon_perdido=?,admin=?,id_admin=?,fecha_cambio_estatus=?,fecha_cierre=?,comentario=?,empresa_vs_perdido=?,id_equipo_vendido=?,anio_actual=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cotizacion=?`,[name,maybeId(b.id_cliente),maybeId(b.id_contacto),client,text(b.contacto,180),text(b.telefono,80),text(b.correo,200),text(b.ciudad,120),text(b.estado,120),text(b.tipo_proyecto,120),Math.max(0,Number(b.numero_equipos||0)||0),text(b.tipo_equipos,200),text(b.informacion_envia,1000),text(b.asesor,30),advisor,text(b.visualiza,80),text(b.anio_mes_cotizacion,20),text(b.mx,30),text(b.fecha_cotizacion,30),text(b.fecha_solicitud,30),text(b.zona,80),text(b.estatus_proyecto,80,'Contacto'),text(b.razon_perdido,1000),text(b.admin,30),admin,text(b.fecha_cambio_estatus,30),text(b.fecha_cierre,30),text(b.comentario,3000),text(b.empresa_vs_perdido,300),text(b.id_equipo_vendido,100),Number(b.anio_actual)||null,uid,qid]);if(Array.isArray(body?.equipos))replaceQuoteEquipment(qid,body.equipos,db);if(String(old.estatus_proyecto)!==String(b.estatus_proyecto))insertHistory(qid,old.estatus_proyecto,b.estatus_proyecto,uid,actor?.iniciales,'CAMBIO_ESTATUS','estatus_proyecto',old.estatus_proyecto,b.estatus_proyecto,text(body?.motivo,300),db);return getQuote(userId,qid,db);}
  function removeQuote(userId,quoteId,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor);db.run('UPDATE ventas_cotizaciones_cor SET activo=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cotizacion=?',[uid,qid]);insertHistory(qid,null,'Borrar',uid,actor?.iniciales,'ELIMINAR','activo','1','0','Baja lógica LAB',db);return{id_cotizacion:qid,activo:false};}
  function replaceQuoteEquipment(qid,equipment,candidateDb){const db=dbOr(candidateDb);if(!Array.isArray(equipment))return;db.run('UPDATE ventas_cotizaciones_equipos_cor SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_cotizacion=?',[qid]);equipment.slice(0,50).forEach((item,index)=>{const type=text(item?.tipo_equipo??item?.tipo,100);const qty=Math.max(0,Number(item?.cantidad??item?.qty??0)||0);if(!type||!qty)return;db.run('INSERT INTO ventas_cotizaciones_equipos_cor(id_cotizacion,tipo_equipo,cantidad,orden,activo) VALUES(?,?,?,?,1)',[qid,type,qty,index+1]);});}
  function insertHistory(qid,previous,next,uid,initials,origin,field,before,after,comment,candidateDb){const db=dbOr(candidateDb);db.run(`INSERT INTO ventas_cotizaciones_historial(id_cotizacion,estatus_anterior,estatus_nuevo,fecha_movimiento,motivo,comentario,campo_origen,valor_anterior,valor_nuevo,id_usuario,iniciales_usuario,origen_movimiento,empresa,activo) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1)`,[qid,text(previous,80),text(next,80),now(),text(comment,300),text(comment,1000),text(field,100),text(before,500),text(after,500),uid,text(initials,20),'LAB_'+String(origin||'CAMBIO').toUpperCase(),'Corellian LAB']);}
  function updateQuoteStatus(userId,quoteId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),status=String(body?.estatus_proyecto??body?.estatus??'').trim();if(!QUOTE_STATUSES.includes(status))throw httpError(400,'Estatus de cotización inválido.','LAB_SALES_STATUS_INVALID');const old=db.query('SELECT estatus_proyecto FROM ventas_cotizaciones_cor WHERE id_cotizacion=?',[qid])[0];const close=status==='Vendido'?text(body?.fecha_cierre,30,new Date().toISOString().slice(0,10)):null;db.run('UPDATE ventas_cotizaciones_cor SET estatus_proyecto=?,razon_perdido=?,empresa_vs_perdido=?,fecha_cambio_estatus=CURRENT_TIMESTAMP,fecha_cierre=COALESCE(?,fecha_cierre),updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cotizacion=?',[status,text(body?.razon_perdido,1000),text(body?.empresa_vs_perdido,300),close,uid,qid]);insertHistory(qid,old?.estatus_proyecto,status,uid,actor?.iniciales,'CAMBIO_ESTATUS','estatus_proyecto',old?.estatus_proyecto,status,text(body?.motivo??body?.comentario,300),db);return getQuote(userId,qid,db);}
  function updateQuoteAssignment(userId,quoteId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),advisor=maybeId(body?.id_asesor),admin=maybeId(body?.id_admin);if(advisor&&!visibleUser(userId,advisor,db)||admin&&!visibleUser(userId,admin,db))throw httpError(403,'La asignación está fuera de tu alcance comercial.','LAB_SALES_ASSIGNMENT_SCOPE');const before=db.query('SELECT id_asesor,id_admin,asesor,admin FROM ventas_cotizaciones_cor WHERE id_cotizacion=?',[qid])[0];const au=advisor?userPublic(db,advisor):null,ad=admin?userPublic(db,admin):null;db.run('UPDATE ventas_cotizaciones_cor SET id_asesor=?,asesor=?,id_admin=?,admin=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_cotizacion=?',[advisor,au?.iniciales||null,admin,ad?.iniciales||null,uid,qid]);insertHistory(qid,null,null,uid,actor?.iniciales,'ASIGNACION','responsables',JSON.stringify(before),JSON.stringify({id_asesor:advisor,id_admin:admin}),'Asignación LAB',db);return getQuote(userId,qid,db);}
  function listHistory(userId,quoteId,query,candidateDb){const db=dbOr(candidateDb),p=pageOf(query,30,100),qid=quoteId?assertQuote(userId,quoteId,db):null;let clauses=['h.activo=1'],params=[];if(qid){clauses.push('h.id_cotizacion=?');params.push(qid);}else{const scope=quoteScopeSql(userId,'q',db);clauses.push(`EXISTS (SELECT 1 FROM ventas_cotizaciones_cor q WHERE q.id_cotizacion=h.id_cotizacion AND q.activo=1 AND ${scope.sql})`);params.push(...scope.params);}const total=Number(db.scalar(`SELECT COUNT(*) FROM ventas_cotizaciones_historial h WHERE ${clauses.join(' AND ')}`,params)||0);const rows=db.query(`SELECT h.* FROM ventas_cotizaciones_historial h WHERE ${clauses.join(' AND ')} ORDER BY datetime(h.fecha_movimiento) DESC,h.id_historial DESC LIMIT ? OFFSET ?`,[...params,p.size,p.offset]);return{historial:rows,data:rows,paginacion:{pagina:p.page,tamano_pagina:p.size,total,total_paginas:total?Math.ceil(total/p.size):0}};}
  function listQuoteComments(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db);return db.query(`SELECT c.*,u.nombre,u.iniciales FROM ventas_cotizaciones_comentarios c LEFT JOIN usuarios u ON u.id_SB=c.id_usuario WHERE c.id_cotizacion=? AND c.activo=1 ORDER BY datetime(c.created_at),c.id_comentario`,[qid]);}
  function addQuoteComment(userId,quoteId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),comment=text(body?.comentario,5000);if(!comment)throw httpError(400,'comentario es obligatorio.');const r=db.run('INSERT INTO ventas_cotizaciones_comentarios(id_cotizacion,id_usuario,comentario,id_comentario_padre,editado,activo) VALUES(?,?,?,?,0,1)',[qid,uid,comment,maybeId(body?.id_comentario_padre)]);return db.query('SELECT * FROM ventas_cotizaciones_comentarios WHERE id_comentario=?',[r.lastInsertRowId])[0];}
  function updateQuoteComment(userId,quoteId,commentId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),cid=id(commentId,'id_comentario'),uid=actorId(actor),comment=text(body?.comentario,5000);if(!comment)throw httpError(400,'comentario es obligatorio.');if(!db.scalar('SELECT 1 FROM ventas_cotizaciones_comentarios WHERE id_comentario=? AND id_cotizacion=? AND activo=1',[cid,qid]))throw httpError(404,'Comentario no encontrado.');db.run('UPDATE ventas_cotizaciones_comentarios SET comentario=?,editado=1,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=?',[comment,cid]);return db.query('SELECT * FROM ventas_cotizaciones_comentarios WHERE id_comentario=?',[cid])[0];}
  function removeQuoteComment(userId,quoteId,commentId,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),cid=id(commentId,'id_comentario');if(!db.scalar('SELECT 1 FROM ventas_cotizaciones_comentarios WHERE id_comentario=? AND id_cotizacion=? AND activo=1',[cid,qid]))throw httpError(404,'Comentario no encontrado.');db.run('UPDATE ventas_cotizaciones_comentarios SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=?',[cid]);db.run('UPDATE ventas_cotizaciones_archivos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=?',[cid]);return{id_comentario:cid,activo:false};}
  function listQuoteFiles(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db);return db.query('SELECT * FROM ventas_cotizaciones_archivos WHERE id_cotizacion=? AND activo=1 ORDER BY datetime(created_at) DESC,id_archivo DESC',[qid]);}
  async function addQuoteFile(userId,quoteId,body,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),file=collectFiles(body)[0];if(!file)throw httpError(400,'Debes adjuntar un archivo.','LAB_FILE_REQUIRED');const stored=await root.ManttoLabBlobStore.put(file,{prefix:`ventas/cotizaciones/${qid}`,metadata:{id_cotizacion:qid,id_usuario:uid}});const name=stored.name||file.name||'archivo',ext=(name.split('.').pop()||'').toLowerCase();const r=await db.run(`INSERT INTO ventas_cotizaciones_archivos(id_cotizacion,id_comentario,id_usuario,nombre_archivo,nombre_original,extension,mime_type,tamanio_bytes,storage_provider,storage_blob_name,tipo_archivo,descripcion,version_numero,activo) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,1)`,[qid,maybeId(body?.id_comentario),uid,name,name,ext,stored.type,stored.size,'LAB_INDEXEDDB',stored.key,text(body?.tipo_archivo,80,'COTIZACION'),text(body?.descripcion,500)]);return db.query('SELECT * FROM ventas_cotizaciones_archivos WHERE id_archivo=?',[r.lastInsertRowId])[0];}
  async function quoteFileAccess(userId,quoteId,fileId,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_cotizaciones_archivos WHERE id_archivo=? AND id_cotizacion=? AND activo=1',[fid,qid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider!=='LAB_INDEXEDDB'||!row.storage_blob_name)throw httpError(410,'El archivo histórico no está disponible en el Blob Store local del LAB.','LAB_LEGACY_FILE_UNAVAILABLE');const access=await root.ManttoLabBlobStore.accessUrl(row.storage_blob_name);if(!access)throw httpError(410,'El contenido del archivo local no está disponible.','LAB_BLOB_NOT_FOUND');return{...row,...access};}
  async function removeQuoteFile(userId,quoteId,fileId,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_cotizaciones_archivos WHERE id_archivo=? AND id_cotizacion=? AND activo=1',[fid,qid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider==='LAB_INDEXEDDB'&&row.storage_blob_name)await root.ManttoLabBlobStore.remove(row.storage_blob_name);await db.run('UPDATE ventas_cotizaciones_archivos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[fid]);return{id_archivo:fid,activo:false};}
  async function setInterest(userId,quoteId,active,actor,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db),uid=actorId(actor),on=bool(active);const type=on?'PROYECTO_INTERES_ACTIVADO':'PROYECTO_INTERES_DESACTIVADO';const current=interestMap(uid,[qid],db).has(String(qid));if(current===on)return{ok:true,source:'lab-sqlite',id_cotizacion:qid,proyecto_interes:on,personal:true,cambio:false};const quote=db.query('SELECT nombre_proyecto,cliente,estatus_proyecto FROM ventas_cotizaciones_cor WHERE id_cotizacion=?',[qid])[0];const r=await db.run(`INSERT INTO usuario_interacciones(id_usuario,tipo_interaccion,modulo,entidad,id_referencia,titulo,descripcion,empresa_contexto,ruta_destino,payload_json,detalle_json,metodo_http,endpoint,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[uid,type,'ventas-cotizaciones','cotizacion',String(qid),on?'Marcaste Proyecto de interés':'Quitaste Proyecto de interés',quote?.nombre_proyecto||quote?.cliente||`Cotización ${qid}`,actor?.empresa||null,'ventas-cotizaciones-detalle',JSON.stringify({activo:on}),JSON.stringify(quote||{}),'PUT',`/api/ventas/cotizaciones/${qid}/interes`,'LAB DGB Browser']);return{ok:true,source:'lab-sqlite',id_cotizacion:qid,proyecto_interes:on,personal:true,cambio:true,id_interaccion:Number(r.lastInsertRowId)};}
  function getInterest(userId,quoteId,candidateDb){const db=dbOr(candidateDb),qid=assertQuote(userId,quoteId,db);return{ok:true,source:'lab-sqlite',id_cotizacion:qid,proyecto_interes:interestMap(userId,[qid],db).has(String(qid)),personal:true};}
  function listInterests(userId,query,candidateDb){const list=listQuotes(userId,{...query,page:1,page_size:100},candidateDb).cotizaciones,ids=interestMap(userId,list.map(r=>r.id_cotizacion),candidateDb),rows=list.filter(r=>ids.has(String(r.id_cotizacion)));const p=pageOf(query,30,30),slice=rows.slice(p.offset,p.offset+p.size);return{ok:true,source:'lab-sqlite',personal:true,data:slice,total:rows.length,paginacion:{pagina:p.page,tamano_pagina:p.size,total:rows.length,total_paginas:rows.length?Math.ceil(rows.length/p.size):0},alcance:coreScope(userId,candidateDb)};}

  function prospectVisible(userId,prospectId,candidateDb){const db=dbOr(candidateDb),pid=id(prospectId,'id_pros'),scope=prospectScopeSql(userId,'p',db);return Boolean(db.scalar(`SELECT 1 FROM ventas_prospecciones p WHERE p.id_pros=? AND p.activo=1 AND ${scope.sql} LIMIT 1`,[pid,...scope.params]));}
  function assertProspect(userId,prospectId,candidateDb){const pid=id(prospectId,'id_pros');if(!prospectVisible(userId,pid,candidateDb))throw httpError(404,'Prospección no encontrada o fuera de tu alcance.','LAB_SALES_PROSPECT_NOT_FOUND');return pid;}
  function prospectListWhere(userId,query,candidateDb,options={}){
    const db=dbOr(candidateDb),scope=prospectScopeSql(userId,'p',db),clauses=['p.activo=1',scope.sql],params=[...scope.params];
    const search=text(query?.q??query?.search??query?.buscar,180);
    if(search){const like=`%${search}%`;clauses.push('(p.empresa LIKE ? OR p.proyecto LIKE ? OR p.contacto LIKE ? OR p.ciudad LIKE ? OR p.estado LIKE ?)');params.push(like,like,like,like,like);}
    const year=Number(query?.anio??query?.year);if(Number.isInteger(year)&&year>=1900&&year<=2200){clauses.push("substr(COALESCE(p.fecha_visita,''),1,4)=?");params.push(String(year));}
    const status=text(query?.estatus,150);if(status){clauses.push("UPPER(TRIM(COALESCE(NULLIF(p.estatus,''),pe.nombre,'')))=UPPER(TRIM(?))");params.push(status);}
    if(maybeId(query?.id_usuario)){clauses.push('p.id_usuario=?');params.push(Number(query.id_usuario));}
    if(maybeId(query?.id_estatus)){clauses.push('p.id_estatus=?');params.push(Number(query.id_estatus));}
    const state=text(query?.estado,150);if(state){clauses.push('p.estado=?');params.push(state);}
    if(options.requireCoordinates===true)clauses.push('p.latitud IS NOT NULL AND p.longitud IS NOT NULL');
    return{db,where:clauses.join(' AND '),params};
  }
  function prospectCatalogs(userId,candidateDb){
    const db=dbOr(candidateDb),scope=prospectScopeSql(userId,'p',db);
    const rows=db.query(`SELECT p.fecha_visita,COALESCE(NULLIF(TRIM(p.estatus),''),pe.nombre) AS estatus,p.estado,p.ciudad,p.tipo_proyecto,p.id_usuario,u.nombre,u.iniciales,u.correo FROM ventas_prospecciones p LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus LEFT JOIN usuarios u ON u.id_SB=p.id_usuario WHERE p.activo=1 AND ${scope.sql}`,[...scope.params]);
    const anios=[...new Set(rows.map(r=>Number(String(r.fecha_visita||'').slice(0,4))).filter(v=>Number.isInteger(v)&&v>=1900&&v<=2200))].sort((a,b)=>b-a);
    const estatus=[...new Set(rows.map(r=>text(r.estatus,150)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
    const estados=[...new Set(rows.map(r=>text(r.estado,150)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
    const ciudades=[...new Set(rows.map(r=>text(r.ciudad,150)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
    const tipos_proyecto=[...new Set(rows.map(r=>text(r.tipo_proyecto,150)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
    const seen=new Set(),usuarios=[];for(const row of rows){const uid=Number(row.id_usuario);if(!Number.isInteger(uid)||uid<=0||seen.has(uid))continue;seen.add(uid);usuarios.push({id_usuario:uid,nombre:row.nombre||row.correo||`Usuario ${uid}`,iniciales:row.iniciales||null,correo:row.correo||null});}usuarios.sort((a,b)=>String(a.nombre||'').localeCompare(String(b.nombre||''),'es'));
    return{anios,estatus,estados,usuarios,ciudades,tipos_proyecto};
  }
  function prospectCaptureCatalogs(candidateDb){
    const db=dbOr(candidateDb);
    const read=(area,element)=>db.query(`SELECT articulo AS value FROM catalogo_general WHERE activo=1 AND LOWER(TRIM(area))=? AND LOWER(TRIM(elemento))=? AND articulo IS NOT NULL AND TRIM(articulo)<>'' ORDER BY orden,articulo`,[area,element]).map(r=>r.value);
    let estados=read('general','estado'),tipos_proyecto=read('ventas','tipo de proyecto');
    if(!estados.length)estados=[...new Set(db.query(`SELECT estado AS value FROM ventas_clientes WHERE activo=1 AND estado IS NOT NULL AND TRIM(estado)<>'' UNION SELECT estado AS value FROM ventas_prospecciones WHERE activo=1 AND estado IS NOT NULL AND TRIM(estado)<>'' ORDER BY value`).map(r=>r.value))];
    if(!tipos_proyecto.length)tipos_proyecto=[...new Set(db.query(`SELECT tipo_proyecto AS value FROM ventas_cotizaciones_cor WHERE activo=1 AND tipo_proyecto IS NOT NULL AND TRIM(tipo_proyecto)<>'' UNION SELECT tipo_proyecto AS value FROM ventas_prospecciones WHERE activo=1 AND tipo_proyecto IS NOT NULL AND TRIM(tipo_proyecto)<>'' ORDER BY value`).map(r=>r.value))];
    return{estados,tipos_proyecto};
  }
  function prospectSources(userId,query,candidateDb){
    const db=dbOr(candidateDb),type=upper(query?.tipo),needle=text(query?.q,150,'')||'',limit=Math.min(50,Math.max(1,Number.parseInt(query?.limit||'30',10)||30)),like=`%${needle}%`;
    if(type==='COTIZADO'){
      const scope=quoteScopeSql(userId,'q',db),params=[...scope.params];
      const clauses=['q.activo=1',scope.sql];if(needle){clauses.push('(q.nombre_proyecto LIKE ? OR q.cliente LIKE ? OR CAST(q.id_cotizacion AS TEXT) LIKE ? OR CAST(q.id_cot_origen AS TEXT) LIKE ?)');params.push(like,like,like,like);}
      return db.query(`SELECT q.id_cotizacion,q.nombre_proyecto AS proyecto,q.cliente AS empresa,q.ciudad,q.estado,q.tipo_proyecto,q.id_cliente,q.id_contacto,q.contacto,vcc.puesto_contacto,q.correo,q.telefono,q.mx,q.estatus_proyecto FROM ventas_cotizaciones_cor q LEFT JOIN ventas_clientes_contactos vcc ON vcc.id_contacto=q.id_contacto WHERE ${clauses.join(' AND ')} ORDER BY q.nombre_proyecto,q.cliente,q.id_cotizacion DESC LIMIT ?`,[...params,limit]);
    }
    if(type==='INSTALACION'){
      const ids=visibleUserIds(userId,db),clauses=['f.activo=1'],params=[];
      if(ids!==null){if(!ids.length)clauses.push('1=0');else{const ph=sqlIn(ids);clauses.push(`(f.id_asesor IN (${ph}) OR f.id_sup IN (${ph}) OR f.id_admin IN (${ph}))`);params.push(...ids,...ids,...ids);}}
      if(needle){clauses.push('(f.proyecto LIKE ? OR f.cliente LIKE ? OR f.ciudad LIKE ? OR CAST(f.id_proyecto AS TEXT) LIKE ?)');params.push(like,like,like,like);}
      return db.query(`SELECT f.id_proyecto,f.id_ins_fl,f.proyecto,f.cliente AS empresa,f.ciudad,f.estado,f.id_asesor,f.id_admin,f.id_sup,NULL AS id_cotizacion,NULL AS id_cliente,NULL AS id_contacto,NULL AS contacto,NULL AS puesto_contacto,NULL AS correo,NULL AS telefono,NULL AS tipo_proyecto FROM ins_fl f WHERE ${clauses.join(' AND ')} ORDER BY f.proyecto,f.id_ins_fl LIMIT ?`,[...params,limit]);
    }
    throw httpError(400,'tipo debe ser INSTALACION o COTIZADO.','LAB_SALES_PROSPECT_SOURCE_TYPE');
  }
  function prospectContacts(userId,clientId,candidateDb){return listContacts(userId,clientId,candidateDb).map(row=>({...row,contacto:row.nombre_contacto||null,correo:row.email||null}));}
  function listProspects(userId,query,candidateDb){
    const base=prospectListWhere(userId,query,candidateDb),p=pageOf(query,30,200),{db,where,params}=base,total=Number(db.scalar(`SELECT COUNT(*) FROM ventas_prospecciones p LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus WHERE ${where}`,params)||0);
    const rows=db.query(`SELECT p.*,COALESCE(NULLIF(TRIM(p.estatus),''),pe.nombre) AS estatus,u.nombre AS usuario_nombre,u.iniciales AS usuario_iniciales,u.correo AS usuario_correo FROM ventas_prospecciones p LEFT JOIN usuarios u ON u.id_SB=p.id_usuario LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus WHERE ${where} ORDER BY datetime(p.fecha_visita) DESC,p.id_pros DESC LIMIT ? OFFSET ?`,[...params,p.size,p.offset]);
    const totalPages=Math.max(1,Math.ceil(total/p.size));return{prospecciones:rows,data:rows,pagination:{page:p.page,page_size:p.size,total,total_pages:totalPages},paginacion:{pagina:p.page,tamano_pagina:p.size,total,total_paginas:totalPages}};
  }
  function prospectMap(userId,query,candidateDb){const base=prospectListWhere(userId,query,candidateDb,{requireCoordinates:true}),{db,where,params}=base;return db.query(`SELECT p.*,COALESCE(NULLIF(TRIM(p.estatus),''),pe.nombre) AS estatus,u.nombre AS usuario_nombre,u.iniciales AS usuario_iniciales,u.correo AS usuario_correo FROM ventas_prospecciones p LEFT JOIN usuarios u ON u.id_SB=p.id_usuario LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus WHERE ${where} ORDER BY datetime(p.fecha_visita) DESC,p.id_pros DESC LIMIT 5000`,params);}
  function getProspect(userId,prospectId,candidateDb){const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db),row=db.query(`SELECT p.*,COALESCE(NULLIF(TRIM(p.estatus),''),pe.nombre) AS estatus,u.nombre AS usuario_nombre,u.iniciales AS usuario_iniciales,u.correo AS usuario_correo,vc.nombre_empresa AS cliente_nombre,vcc.nombre_contacto AS contacto_catalogo_nombre,vcc.puesto_contacto AS contacto_catalogo_puesto,vcc.email AS contacto_catalogo_correo,vcc.telefono AS contacto_catalogo_telefono,q.nombre_proyecto AS cotizacion_proyecto,q.cliente AS cotizacion_cliente FROM ventas_prospecciones p LEFT JOIN usuarios u ON u.id_SB=p.id_usuario LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus LEFT JOIN ventas_clientes vc ON vc.id_cliente=p.id_cliente LEFT JOIN ventas_clientes_contactos vcc ON vcc.id_contacto=p.id_contacto LEFT JOIN ventas_cotizaciones_cor q ON q.id_cotizacion=p.id_cotizacion WHERE p.id_pros=?`,[pid])[0],comments=db.query('SELECT c.*,u.nombre AS usuario_nombre,u.iniciales AS usuario_iniciales FROM ventas_prospeccion_comentarios c LEFT JOIN usuarios u ON u.id_SB=c.id_usuario WHERE c.id_pros=? AND c.activo=1 ORDER BY datetime(COALESCE(c.fecha_hora,c.created_at)),c.id_com_pors',[pid]),files=db.query('SELECT * FROM ventas_prospeccion_archivos WHERE id_pros=? AND activo=1 ORDER BY tipo_relacion,COALESCE(id_com_pors,0),orden,id_archivo',[pid]);return{...row,comentarios:comments,archivos:files};}
  function prospectKpis(userId,query,candidateDb){const base=prospectListWhere(userId,query,candidateDb),{db,where,params}=base,row=db.query(`SELECT COUNT(*) AS visitas,SUM(CASE WHEN p.latitud IS NOT NULL AND p.longitud IS NOT NULL THEN 1 ELSE 0 END) AS con_ubicacion,SUM(CASE WHEN substr(COALESCE(p.fecha_visita,''),1,4)=strftime('%Y','now') THEN 1 ELSE 0 END) AS este_anio,COUNT(DISTINCT NULLIF(TRIM(COALESCE(NULLIF(p.estatus,''),pe.nombre,'')),'')) AS estatus_activos FROM ventas_prospecciones p LEFT JOIN ventas_prospeccion_estatus pe ON pe.id_estatus=p.id_estatus WHERE ${where}`,params)[0]||{};return{kpis:{visitas:Number(row.visitas||0),con_ubicacion:Number(row.con_ubicacion||0),este_anio:Number(row.este_anio||0),estatus_activos:Number(row.estatus_activos||0)}};}
  async function createProspect(body,actor,candidateDb){
    const db=dbOr(candidateDb),uid=actorId(actor),b=values(body),classification=upper(b.clasificacion||'NUEVO');if(!['NUEVO','INSTALACION','COTIZADO'].includes(classification))throw httpError(400,'clasificacion debe ser NUEVO, INSTALACION o COTIZADO.');
    let company=text(b.empresa,255),project=text(b.proyecto,255),installationId=text(b.id_proyecto_instalacion,255),quoteId=maybeId(b.id_cotizacion),clientId=maybeId(b.id_cliente),contactId=maybeId(b.id_contacto),contact=text(b.contacto,255),position=text(b.puesto_contacto,150),email=text(b.correo,255),phone=text(b.telefono,100);
    if(!company||!project)throw httpError(400,'empresa y proyecto son obligatorios.');
    if(classification==='INSTALACION'){
      if(!installationId)throw httpError(400,'Selecciona un proyecto de Instalaciones.');const source=prospectSources(uid,{tipo:'INSTALACION',q:''},db).find(row=>String(row.id_proyecto)===String(installationId));if(!source)throw httpError(404,'Proyecto de Instalaciones no encontrado o fuera de alcance.');
    }
    if(classification==='COTIZADO'){
      if(!quoteId)throw httpError(400,'Selecciona una cotización.');const quote=getQuote(uid,quoteId,db);clientId=clientId||maybeId(quote.id_cliente);contactId=contactId||maybeId(quote.id_contacto);company=company||text(quote.cliente,255);project=project||text(quote.nombre_proyecto,255);
    }
    if(clientId&&contactId){const c=prospectContacts(uid,clientId,db).find(row=>Number(row.id_contacto)===Number(contactId));if(!c)throw httpError(400,'El contacto seleccionado no pertenece al cliente visible.');contact=c.contacto||contact;position=c.puesto_contacto||position;email=c.correo||email;phone=c.telefono||phone;}
    const mode=upper(b.contact_mode);if(clientId&&mode==='NEW'&&contact){const created=createContact(uid,clientId,{nombre_contacto:contact,puesto_contacto:position,email,telefono:phone,contacto_principal:0},actor,db);contactId=Number(created.id_contacto);}
    const status=maybeId(b.id_estatus)||Number(db.scalar('SELECT id_estatus FROM ventas_prospeccion_estatus WHERE activo=1 ORDER BY orden LIMIT 1')||0)||null,srow=status?db.query('SELECT nombre FROM ventas_prospeccion_estatus WHERE id_estatus=?',[status])[0]:null;
    const r=await db.run(`INSERT INTO ventas_prospecciones(empresa,proyecto,ubicacion,latitud,longitud,contacto,puesto_contacto,correo,telefono,comentario,id_usuario,ciudad,estado,tipo_proyecto,fecha_visita,id_estatus,estatus,fecha_cam_estatus,nuevo,proyecto_activo,proyecto_cotizado,id_proyecto_instalacion,id_cotizacion,id_cliente,id_contacto,activo) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)`,[company,project,text(b.ubicacion,300),Number.isFinite(Number(b.latitud))?Number(b.latitud):null,Number.isFinite(Number(b.longitud))?Number(b.longitud):null,contact,position,email,phone,text(b.comentario,5000),uid,text(b.ciudad,150),text(b.estado,150),text(b.tipo_proyecto,150),text(b.fecha_visita,40,now()),status,srow?.nombre||text(b.estatus,150),now(),1,classification==='INSTALACION'?1:0,classification==='COTIZADO'?1:0,installationId,quoteId,clientId,contactId]);
    const pid=Number(r.lastInsertRowId);for(const file of collectFiles(body).slice(0,4))await addProspectFile(pid,null,file,'VISITA',uid,db);return getProspect(uid,pid,db);
  }
  function updateProspectStatus(userId,prospectId,body,actor,candidateDb){
    const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db);let s=null;
    if(maybeId(body?.id_estatus))s=db.query('SELECT * FROM ventas_prospeccion_estatus WHERE id_estatus=? AND activo=1',[Number(body.id_estatus)])[0]||null;
    if(!s&&text(body?.estatus,150)){const requested=text(body.estatus,150);s=db.query(`SELECT * FROM ventas_prospeccion_estatus WHERE activo=1 AND (UPPER(TRIM(nombre))=UPPER(TRIM(?)) OR UPPER(TRIM(codigo))=UPPER(TRIM(?))) LIMIT 1`,[requested,requested])[0]||null;}
    if(!s)throw httpError(400,'Estatus de prospección inválido.');
    if(upper(s.nombre)==='COTIZADO'||upper(s.codigo)==='COTIZADO'){const current=db.query('SELECT nuevo,id_cotizacion FROM ventas_prospecciones WHERE id_pros=?',[pid])[0];if(Number(current?.nuevo)===1&&!maybeId(current?.id_cotizacion))throw httpError(409,'Relaciona una cotización antes de cambiar una prospección nueva a Cotizado.','LAB_PROSPECT_QUOTE_REQUIRED');}
    db.run('UPDATE ventas_prospecciones SET id_estatus=?,estatus=?,fecha_cam_estatus=CURRENT_TIMESTAMP,nuevo=0,proyecto_activo=CASE WHEN ?=1 THEN 0 ELSE proyecto_activo END,updated_at=CURRENT_TIMESTAMP WHERE id_pros=?',[Number(s.id_estatus),s.nombre,Number(s.es_cierre),pid]);return getProspect(userId,pid,db);
  }
  function linkProspectQuote(userId,prospectId,body,actor,candidateDb){
    const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db),qid=id(body?.id_cotizacion,'id_cotizacion');assertQuote(userId,qid,db);
    const quoted=db.query(`SELECT * FROM ventas_prospeccion_estatus WHERE activo=1 AND (UPPER(TRIM(nombre))='COTIZADO' OR UPPER(TRIM(codigo))='COTIZADO') ORDER BY orden,id_estatus LIMIT 1`)[0]||null;
    db.run('UPDATE ventas_prospecciones SET id_cotizacion=?,proyecto_cotizado=1,nuevo=0,id_estatus=COALESCE(?,id_estatus),estatus=COALESCE(?,estatus),fecha_cam_estatus=CASE WHEN ? IS NOT NULL THEN CURRENT_TIMESTAMP ELSE fecha_cam_estatus END,updated_at=CURRENT_TIMESTAMP WHERE id_pros=?',[qid,quoted?.id_estatus||null,quoted?.nombre||null,quoted?.id_estatus||null,pid]);
    return{prospeccion:getProspect(userId,pid,db),estatus_actualizado:Boolean(quoted)};
  }
  async function addProspectFile(prospectId,commentId,file,relation,userId,candidateDb){const db=dbOr(candidateDb),stored=await root.ManttoLabBlobStore.put(file,{prefix:`ventas/prospeccion/${prospectId}`}),name=stored.name||file.name||'archivo',ext=(name.split('.').pop()||'').toLowerCase();const order=Number(db.scalar('SELECT COALESCE(MAX(orden),0)+1 FROM ventas_prospeccion_archivos WHERE id_pros=? AND activo=1',[prospectId])||1);const r=await db.run(`INSERT INTO ventas_prospeccion_archivos(id_pros,id_com_pors,tipo_relacion,nombre_archivo,nombre_original,mime_type,extension,tamano_bytes,storage_provider,storage_blob_name,orden,es_imagen,activo) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)`,[prospectId,commentId,relation,name,name,stored.type,ext,stored.size,'LAB_INDEXEDDB',stored.key,order,String(stored.type||'').startsWith('image/')?1:0]);return db.query('SELECT * FROM ventas_prospeccion_archivos WHERE id_archivo=?',[r.lastInsertRowId])[0];}
  async function addProspectComment(userId,prospectId,body,actor,candidateDb){const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db),uid=actorId(actor),comment=text(body?.comentario,5000);if(!comment)throw httpError(400,'comentario es obligatorio.');const r=await db.run('INSERT INTO ventas_prospeccion_comentarios(id_pros,id_usuario,comentario,fecha_hora,editado,activo) VALUES(?,?,?,CURRENT_TIMESTAMP,0,1)',[pid,uid,comment]);const cid=Number(r.lastInsertRowId);const files=[];for(const file of collectFiles(body).slice(0,4))files.push(await addProspectFile(pid,cid,file,'COMENTARIO',uid,db));return{comentario:db.query('SELECT * FROM ventas_prospeccion_comentarios WHERE id_com_pors=?',[cid])[0],archivos:files};}
  async function prospectFileAccess(userId,prospectId,fileId,candidateDb){const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_prospeccion_archivos WHERE id_archivo=? AND id_pros=? AND activo=1',[fid,pid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider!=='LAB_INDEXEDDB'||!row.storage_blob_name)throw httpError(410,'El archivo histórico no está disponible en el LAB.','LAB_LEGACY_FILE_UNAVAILABLE');const access=await root.ManttoLabBlobStore.accessUrl(row.storage_blob_name);if(!access)throw httpError(410,'Contenido local no disponible.','LAB_BLOB_NOT_FOUND');return{...row,...access};}
  async function removeProspectFile(userId,prospectId,fileId,candidateDb){const db=dbOr(candidateDb),pid=assertProspect(userId,prospectId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_prospeccion_archivos WHERE id_archivo=? AND id_pros=? AND activo=1',[fid,pid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider==='LAB_INDEXEDDB'&&row.storage_blob_name)await root.ManttoLabBlobStore.remove(row.storage_blob_name);await db.run('UPDATE ventas_prospeccion_archivos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[fid]);return{id_archivo:fid,activo:false};}

  function networkVisible(userId,networkId,candidateDb){const db=dbOr(candidateDb),nid=id(networkId,'id_redes'),scope=networkScopeSql(userId,'r',db);return Boolean(db.scalar(`SELECT 1 FROM ventas_redes r WHERE r.id_redes=? AND r.activo=1 AND ${scope.sql} LIMIT 1`,[nid,...scope.params]));}
  function assertNetwork(userId,networkId,candidateDb){const nid=id(networkId,'id_redes');if(!networkVisible(userId,nid,candidateDb))throw httpError(404,'Registro de Redes no encontrado o fuera de tu alcance.','LAB_SALES_NETWORK_NOT_FOUND');return nid;}
  function networkCatalogs(userId,candidateDb){
    const db=dbOr(candidateDb);
    const read=(area,element,legacyElement)=>{let rows=db.query(`SELECT id_catalogo,area,elemento,articulo,descripcion,orden FROM catalogo_general WHERE activo=1 AND LOWER(TRIM(area))=LOWER(TRIM(?)) AND LOWER(TRIM(elemento))=LOWER(TRIM(?)) ORDER BY orden,articulo,id_catalogo`,[area,element]);if(!rows.length&&legacyElement)rows=db.query(`SELECT id_catalogo,area,elemento,articulo,descripcion,orden FROM catalogo_general WHERE activo=1 AND UPPER(TRIM(area))='REDES' AND UPPER(TRIM(elemento))=? ORDER BY orden,articulo,id_catalogo`,[legacyElement]);return rows;};
    return{contacto_via:read('Ventas','Tipo Contacto','VIA_CONTACTO'),estados:read('General','Estado','ESTADO'),solicitudes:read('Ventas','Soli Red','SOLICITUD'),estatus:read('Ventas','Estatus Pros','ESTATUS'),usuarios:visibleCommercialUsers(userId,db)};
  }
  function listNetworks(userId,query,candidateDb){
    const db=dbOr(candidateDb),scope=networkScopeSql(userId,'r',db),p=pageOf(query,50,500),clauses=['r.activo=1',scope.sql],params=[...scope.params],search=text(query?.search??query?.buscar,250);
    if(search){const like=`%${search}%`;clauses.push('(r.nombre_contacto LIKE ? OR r.email LIKE ? OR r.telefono LIKE ? OR r.nombre_empresa LIKE ? OR r.ciudad LIKE ? OR r.nombre_proyecto LIKE ? OR r.informacion_enviada LIKE ? OR cv.articulo LIKE ? OR ce.articulo LIKE ? OR cs.articulo LIKE ? OR cest.articulo LIKE ? OR u.nombre LIKE ? OR u.iniciales LIKE ? OR q.nombre_proyecto LIKE ? OR q.cliente LIKE ?)');params.push(...Array(15).fill(like));}
    for(const f of ['id_contacto_via','id_estado','id_solicitud','id_usuario_asignado','created_by','id_estatus','id_cotizacion'])if(maybeId(query?.[f])){clauses.push(`r.${f}=?`);params.push(Number(query[f]));}
    if(bool(query?.sin_asignar))clauses.push('r.id_usuario_asignado IS NULL');if(bool(query?.con_asignacion))clauses.push('r.id_usuario_asignado IS NOT NULL');if(bool(query?.sin_cotizacion))clauses.push('r.id_cotizacion IS NULL');if(bool(query?.con_cotizacion))clauses.push('r.id_cotizacion IS NOT NULL');
    const where=clauses.join(' AND '),joins=` LEFT JOIN catalogo_general cv ON cv.id_catalogo=r.id_contacto_via LEFT JOIN catalogo_general ce ON ce.id_catalogo=r.id_estado LEFT JOIN catalogo_general cs ON cs.id_catalogo=r.id_solicitud LEFT JOIN catalogo_general cest ON cest.id_catalogo=r.id_estatus LEFT JOIN usuarios u ON u.id_SB=r.id_usuario_asignado LEFT JOIN usuarios cu ON cu.id_SB=r.created_by LEFT JOIN ventas_cotizaciones_cor q ON q.id_cotizacion=r.id_cotizacion`,total=Number(db.scalar(`SELECT COUNT(DISTINCT r.id_redes) FROM ventas_redes r${joins} WHERE ${where}`,params)||0);
    const rows=db.query(`SELECT r.*,cv.articulo AS contacto_via,cv.descripcion AS contacto_via_descripcion,ce.articulo AS estado,cs.articulo AS solicitud,cs.descripcion AS solicitud_descripcion,cest.articulo AS estatus,cest.descripcion AS estatus_descripcion,u.nombre AS usuario_asignado_nombre,u.iniciales AS usuario_asignado_iniciales,u.puesto AS usuario_asignado_puesto,u.area AS usuario_asignado_area,u.empresa AS usuario_asignado_empresa,cu.nombre AS creado_por_nombre,cu.iniciales AS creado_por_iniciales,q.nombre_proyecto AS cotizacion_nombre,q.cliente AS cotizacion_cliente,q.estatus_proyecto AS cotizacion_estatus,(SELECT COUNT(*) FROM ventas_redes_archivos a WHERE a.id_redes=r.id_redes AND a.activo=1) AS total_evidencias,(SELECT COUNT(*) FROM ventas_redes_comentarios c WHERE c.id_redes=r.id_redes AND c.activo=1) AS total_comentarios FROM ventas_redes r${joins} WHERE ${where} ORDER BY datetime(r.created_at) DESC,r.id_redes DESC LIMIT ? OFFSET ?`,[...params,p.size,p.offset]);
    const totalPages=Math.max(1,Math.ceil(total/p.size));return{registros:rows,data:rows,pagination:{page:p.page,page_size:p.size,total,total_pages:totalPages},paginacion:{pagina:p.page,tamano_pagina:p.size,total,total_paginas:totalPages}};
  }
  function getNetwork(userId,networkId,candidateDb){
    const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),scope=networkScopeSql(userId,'r',db),row=db.query(`SELECT r.*,cv.articulo AS contacto_via,cv.descripcion AS contacto_via_descripcion,ce.articulo AS estado,cs.articulo AS solicitud,cs.descripcion AS solicitud_descripcion,cest.articulo AS estatus,cest.descripcion AS estatus_descripcion,u.nombre AS usuario_asignado_nombre,u.iniciales AS usuario_asignado_iniciales,u.puesto AS usuario_asignado_puesto,u.area AS usuario_asignado_area,u.empresa AS usuario_asignado_empresa,cu.nombre AS creado_por_nombre,cu.iniciales AS creado_por_iniciales,q.nombre_proyecto AS cotizacion_nombre,q.cliente AS cotizacion_cliente,q.estatus_proyecto AS cotizacion_estatus FROM ventas_redes r LEFT JOIN catalogo_general cv ON cv.id_catalogo=r.id_contacto_via LEFT JOIN catalogo_general ce ON ce.id_catalogo=r.id_estado LEFT JOIN catalogo_general cs ON cs.id_catalogo=r.id_solicitud LEFT JOIN catalogo_general cest ON cest.id_catalogo=r.id_estatus LEFT JOIN usuarios u ON u.id_SB=r.id_usuario_asignado LEFT JOIN usuarios cu ON cu.id_SB=r.created_by LEFT JOIN ventas_cotizaciones_cor q ON q.id_cotizacion=r.id_cotizacion WHERE r.id_redes=? AND r.activo=1 AND ${scope.sql} LIMIT 1`,[nid,...scope.params])[0];if(!row)throw httpError(404,'Registro de Redes no encontrado o fuera de tu alcance.');return{...row,archivos:listNetworkFiles(userId,nid,db),comentarios:listNetworkComments(userId,nid,db)};
  }
  async function createNetwork(body,actor,candidateDb){const db=dbOr(candidateDb),uid=actorId(actor),b=values(body),assigned=maybeId(b.id_usuario_asignado)||uid;if(!visibleUser(uid,assigned,db))throw httpError(403,'Responsable fuera de alcance comercial.');const r=await db.run(`INSERT INTO ventas_redes(nombre_contacto,id_contacto_via,email,telefono,id_estado,nombre_empresa,ciudad,nombre_proyecto,informacion_enviada,id_solicitud,id_usuario_asignado,created_by,id_estatus,fecha_cambio_estatus,id_cotizacion,activo,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,?,1,?)`,[text(b.nombre_contacto,180),maybeId(b.id_contacto_via),text(b.email,200),text(b.telefono,80),maybeId(b.id_estado),text(b.nombre_empresa,200),text(b.ciudad,120),text(b.nombre_proyecto,220),text(b.informacion_enviada,3000),maybeId(b.id_solicitud),assigned,uid,maybeId(b.id_estatus),maybeId(b.id_cotizacion),uid]);const nid=Number(r.lastInsertRowId);for(const file of collectFiles(body).slice(0,2))await addNetworkFile(nid,file,uid,db);return getNetwork(uid,nid,db);}
  function updateNetwork(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),old=db.query('SELECT * FROM ventas_redes WHERE id_redes=?',[nid])[0],b={...old,...values(body)},assigned=maybeId(b.id_usuario_asignado);if(assigned&&!visibleUser(userId,assigned,db))throw httpError(403,'Responsable fuera de alcance comercial.');db.run(`UPDATE ventas_redes SET nombre_contacto=?,id_contacto_via=?,email=?,telefono=?,id_estado=?,nombre_empresa=?,ciudad=?,nombre_proyecto=?,informacion_enviada=?,id_solicitud=?,id_usuario_asignado=?,id_estatus=?,id_cotizacion=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_redes=?`,[text(b.nombre_contacto,180),maybeId(b.id_contacto_via),text(b.email,200),text(b.telefono,80),maybeId(b.id_estado),text(b.nombre_empresa,200),text(b.ciudad,120),text(b.nombre_proyecto,220),text(b.informacion_enviada,3000),maybeId(b.id_solicitud),assigned,maybeId(b.id_estatus),maybeId(b.id_cotizacion),uid,nid]);return getNetwork(userId,nid,db);}
  function removeNetwork(userId,networkId,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor);db.run('UPDATE ventas_redes SET activo=0,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_redes=?',[uid,nid]);return{id_redes:nid,activo:false};}
  function updateNetworkStatus(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),status=id(body?.id_estatus,'id_estatus');db.run('UPDATE ventas_redes SET id_estatus=?,fecha_cambio_estatus=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_redes=?',[status,uid,nid]);return getNetwork(userId,nid,db);}
  function updateNetworkAssignment(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),assigned=id(body?.id_usuario_asignado,'id_usuario_asignado');if(!visibleUser(userId,assigned,db))throw httpError(403,'Responsable fuera de alcance comercial.');db.run('UPDATE ventas_redes SET id_usuario_asignado=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_redes=?',[assigned,uid,nid]);return getNetwork(userId,nid,db);}
  function updateNetworkQuotation(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),qid=maybeId(body?.id_cotizacion);if(qid)assertQuote(userId,qid,db);db.run('UPDATE ventas_redes SET id_cotizacion=?,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id_redes=?',[qid,uid,nid]);return getNetwork(userId,nid,db);}
  function listNetworkFiles(userId,networkId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db);return db.query('SELECT * FROM ventas_redes_archivos WHERE id_redes=? AND activo=1 ORDER BY orden_archivo,id_archivo',[nid]);}
  async function addNetworkFile(networkId,file,userId,candidateDb){const db=dbOr(candidateDb),order=Number(db.scalar('SELECT COALESCE(MAX(orden_archivo),0)+1 FROM ventas_redes_archivos WHERE id_redes=? AND activo=1',[networkId])||1);if(order>2)throw httpError(409,'Redes admite máximo dos evidencias activas.','LAB_REDES_FILE_LIMIT');const stored=await root.ManttoLabBlobStore.put(file,{prefix:`ventas/redes/${networkId}`}),name=stored.name||file.name||'archivo',ext=(name.split('.').pop()||'').toLowerCase();const r=await db.run(`INSERT INTO ventas_redes_archivos(id_redes,orden_archivo,nombre_archivo,nombre_original,extension,mime_type,tamanio_bytes,storage_provider,storage_blob_name,tipo_archivo,id_usuario,activo) VALUES(?,?,?,?,?,?,?,?,?,?,?,1)`,[networkId,order,name,name,ext,stored.type,stored.size,'LAB_INDEXEDDB',stored.key,'EVIDENCIA',userId]);return db.query('SELECT * FROM ventas_redes_archivos WHERE id_archivo=?',[r.lastInsertRowId])[0];}
  async function uploadNetworkFiles(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),out=[];for(const file of collectFiles(body).slice(0,2))out.push(await addNetworkFile(nid,file,uid,db));if(!out.length)throw httpError(400,'Debes adjuntar al menos un archivo.');return out;}
  async function networkFileAccess(userId,networkId,fileId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_redes_archivos WHERE id_archivo=? AND id_redes=? AND activo=1',[fid,nid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider!=='LAB_INDEXEDDB'||!row.storage_blob_name)throw httpError(410,'El archivo histórico no está disponible en el LAB.','LAB_LEGACY_FILE_UNAVAILABLE');const access=await root.ManttoLabBlobStore.accessUrl(row.storage_blob_name);if(!access)throw httpError(410,'Contenido local no disponible.');return{...row,...access};}
  async function removeNetworkFile(userId,networkId,fileId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),fid=id(fileId,'id_archivo'),row=db.query('SELECT * FROM ventas_redes_archivos WHERE id_archivo=? AND id_redes=? AND activo=1',[fid,nid])[0];if(!row)throw httpError(404,'Archivo no encontrado.');if(row.storage_provider==='LAB_INDEXEDDB'&&row.storage_blob_name)await root.ManttoLabBlobStore.remove(row.storage_blob_name);await db.run('UPDATE ventas_redes_archivos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[fid]);return{id_archivo:fid,activo:false};}
  function listNetworkComments(userId,networkId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db);return db.query(`SELECT c.*,u.nombre,u.iniciales FROM ventas_redes_comentarios c LEFT JOIN usuarios u ON u.id_SB=c.id_usuario WHERE c.id_redes=? AND c.activo=1 ORDER BY datetime(c.fecha_hora),c.id_comentario`,[nid]).map(c=>({...c,adjuntos:db.query('SELECT * FROM ventas_redes_comentarios_adjuntos WHERE id_comentario=? AND activo=1 ORDER BY id_adjunto',[c.id_comentario])}));}
  async function createNetworkComment(userId,networkId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),uid=actorId(actor),comment=text(body?.comentario,5000);if(!comment)throw httpError(400,'comentario es obligatorio.');const r=await db.run('INSERT INTO ventas_redes_comentarios(id_redes,id_usuario,comentario,tipo_evento,fecha_hora,editado,activo) VALUES(?,?,?,\'COMENTARIO\',CURRENT_TIMESTAMP,0,1)',[nid,uid,comment]),cid=Number(r.lastInsertRowId);for(const file of collectFiles(body).slice(0,4))await addNetworkCommentAttachment(cid,file,uid,db);return listNetworkComments(userId,nid,db).find(x=>Number(x.id_comentario)===cid);}
  function updateNetworkComment(userId,networkId,commentId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),cid=id(commentId,'id_comentario'),comment=text(body?.comentario,5000);if(!comment)throw httpError(400,'comentario es obligatorio.');if(!db.scalar('SELECT 1 FROM ventas_redes_comentarios WHERE id_comentario=? AND id_redes=? AND activo=1',[cid,nid]))throw httpError(404,'Comentario no encontrado.');db.run('UPDATE ventas_redes_comentarios SET comentario=?,editado=1,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=?',[comment,cid]);return listNetworkComments(userId,nid,db).find(x=>Number(x.id_comentario)===cid);}
  async function removeNetworkComment(userId,networkId,commentId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),cid=id(commentId,'id_comentario');const at=db.query('SELECT storage_provider,storage_blob_name FROM ventas_redes_comentarios_adjuntos WHERE id_comentario=? AND activo=1',[cid]);for(const row of at)if(row.storage_provider==='LAB_INDEXEDDB'&&row.storage_blob_name)await root.ManttoLabBlobStore.remove(row.storage_blob_name);await db.run('UPDATE ventas_redes_comentarios SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=? AND id_redes=?',[cid,nid]);await db.run('UPDATE ventas_redes_comentarios_adjuntos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_comentario=?',[cid]);return{id_comentario:cid,activo:false};}
  async function addNetworkCommentAttachment(commentId,file,userId,candidateDb){const db=dbOr(candidateDb),stored=await root.ManttoLabBlobStore.put(file,{prefix:`ventas/redes/comentarios/${commentId}`}),name=stored.name||file.name||'archivo',ext=(name.split('.').pop()||'').toLowerCase();const r=await db.run(`INSERT INTO ventas_redes_comentarios_adjuntos(id_comentario,nombre_archivo,nombre_original,extension,mime_type,tamanio_bytes,storage_provider,storage_blob_name,tipo_archivo,id_usuario,activo) VALUES(?,?,?,?,?,?,?,?,?,?,1)`,[commentId,name,name,ext,stored.type,stored.size,'LAB_INDEXEDDB',stored.key,'ADJUNTO',userId]);return db.query('SELECT * FROM ventas_redes_comentarios_adjuntos WHERE id_adjunto=?',[r.lastInsertRowId])[0];}
  async function addNetworkCommentAttachments(userId,networkId,commentId,body,actor,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),cid=id(commentId,'id_comentario'),uid=actorId(actor);if(!db.scalar('SELECT 1 FROM ventas_redes_comentarios WHERE id_comentario=? AND id_redes=? AND activo=1',[cid,nid]))throw httpError(404,'Comentario no encontrado.');const out=[];for(const file of collectFiles(body).slice(0,4))out.push(await addNetworkCommentAttachment(cid,file,uid,db));if(!out.length)throw httpError(400,'Debes adjuntar al menos un archivo.');return out;}
  async function networkAttachmentAccess(userId,networkId,commentId,attachmentId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),cid=id(commentId,'id_comentario'),aid=id(attachmentId,'id_adjunto'),row=db.query(`SELECT a.* FROM ventas_redes_comentarios_adjuntos a JOIN ventas_redes_comentarios c ON c.id_comentario=a.id_comentario WHERE a.id_adjunto=? AND a.id_comentario=? AND c.id_redes=? AND a.activo=1 AND c.activo=1`,[aid,cid,nid])[0];if(!row)throw httpError(404,'Adjunto no encontrado.');if(row.storage_provider!=='LAB_INDEXEDDB'||!row.storage_blob_name)throw httpError(410,'El archivo histórico no está disponible en el LAB.','LAB_LEGACY_FILE_UNAVAILABLE');const access=await root.ManttoLabBlobStore.accessUrl(row.storage_blob_name);if(!access)throw httpError(410,'Contenido local no disponible.');return{...row,...access};}
  async function removeNetworkAttachment(userId,networkId,commentId,attachmentId,candidateDb){const db=dbOr(candidateDb),nid=assertNetwork(userId,networkId,db),cid=id(commentId,'id_comentario'),aid=id(attachmentId,'id_adjunto'),row=db.query(`SELECT a.* FROM ventas_redes_comentarios_adjuntos a JOIN ventas_redes_comentarios c ON c.id_comentario=a.id_comentario WHERE a.id_adjunto=? AND a.id_comentario=? AND c.id_redes=? AND a.activo=1`,[aid,cid,nid])[0];if(!row)throw httpError(404,'Adjunto no encontrado.');if(row.storage_provider==='LAB_INDEXEDDB'&&row.storage_blob_name)await root.ManttoLabBlobStore.remove(row.storage_blob_name);await db.run('UPDATE ventas_redes_comentarios_adjuntos SET activo=0,updated_at=CURRENT_TIMESTAMP WHERE id_adjunto=?',[aid]);return{id_adjunto:aid,activo:false};}

  function dashboardUsers(userId,candidateDb){return{usuarios:visibleCommercialUsers(userId,candidateDb),visibilidad:coreScope(userId,candidateDb),alcance:coreScope(userId,candidateDb)};}
  function dashboardSelection(userId,query,candidateDb){const db=dbOr(candidateDb),raw=String(query?.usuario_id??'').trim().toLowerCase(),visible=visibleCommercialUsers(userId,db);if(!raw||raw==='todos'||raw==='all')return{mode:'ALL',userId:null,users:visible};const selected=id(raw,'usuario_id');const row=visible.find(item=>Number(item.id_usuario||item.id_SB)===selected);if(!row)throw httpError(403,'El responsable seleccionado queda fuera de tu Alcance de Información de Ventas.','LAB_SALES_DASHBOARD_SCOPE');return{mode:'USER',userId:selected,users:[row]};}
  function dashboardKpis(userId,query,candidateDb){const db=dbOr(candidateDb),selection=dashboardSelection(userId,query,db),effectiveQuery=selection.userId?{...query,id_asesor:selection.userId}:{...query},k=kpisQuotes(userId,effectiveQuery,db).kpis;return{modo:selection.mode,usuario_id:selection.userId,usuarios_incluidos:selection.users.length,anio:Number(query?.anio||new Date().getFullYear()),kpis:{cotizados:{cotizaciones:k.total_cotizaciones,equipos:k.total_equipos},vendidos:{cotizaciones:k.vendidas,equipos:k.equipos_vendidos},perdidos:{cotizaciones:k.perdidas,equipos:k.equipos_perdidos}},anios_disponibles:quoteCatalogs(userId,db).anios};}
  function dashboardTables(userId,query,candidateDb){const db=dbOr(candidateDb),selection=dashboardSelection(userId,query,db),selected=selection.users[0]||null,common={...query,page:1,page_size:100},commercialQuery=selection.userId?{...common,id_asesor:selection.userId}:common,clientQuery=selection.userId?{...common,iniciales:selected?.iniciales||''}:common,prospectQuery=selection.userId?{...common,id_usuario:selection.userId}:common,networkQuery=selection.userId?{...common,id_usuario_asignado:selection.userId}:common;return{modo:selection.mode,usuario_id:selection.userId,usuarios_incluidos:selection.users.length,tablas:{clientes:listClients(userId,clientQuery,db).clientes,cotizaciones:listQuotes(userId,commercialQuery,db).cotizaciones,ventas:quoteByStatus(userId,['Vendido'],commercialQuery,db),perdido:quoteByStatus(userId,['Perdido'],commercialQuery,db),prospeccion:listProspects(userId,prospectQuery,db).prospecciones,redes:listNetworks(userId,networkQuery,db).registros},alcance:coreScope(userId,db)};}
  function dashboardOperation(userId,query,candidateDb){const db=dbOr(candidateDb),raw=String(query?.usuario_id??'').trim().toLowerCase(),scopeIds=visibleUserIds(userId,db);let ids=scopeIds;if(raw&&raw!=='todos'&&raw!=='all'){const selected=id(raw,'usuario_id');if(scopeIds!==null&&!scopeIds.includes(selected))throw httpError(403,'El responsable seleccionado queda fuera de tu Alcance de Información de Ventas.','LAB_SALES_DASHBOARD_SCOPE');ids=[selected];}let assigned=[],created=[],logistica=[],instalaciones=[];if(ids===null){assigned=db.query(`SELECT DISTINCT p.* FROM pendientes p JOIN pendientes_usuarios pu ON pu.id_pendiente=p.id_pendiente ORDER BY p.id_pendiente DESC LIMIT 100`);created=db.query(`SELECT p.* FROM pendientes p ORDER BY p.id_pendiente DESC LIMIT 100`);logistica=db.query('SELECT * FROM logistica_produccion WHERE activo=1 ORDER BY id_produccion DESC LIMIT 100');instalaciones=db.query('SELECT * FROM ins_fl WHERE activo=1 ORDER BY id_ins_fl DESC LIMIT 100');}else if(ids.length){const users=db.query(`SELECT id_SB,iniciales,correo FROM usuarios WHERE estado=1 AND id_SB IN (${sqlIn(ids)})`,ids),initials=[...new Set(users.map(r=>text(r.iniciales,50)).filter(Boolean))],emails=[...new Set(users.map(r=>text(r.correo,200)).filter(Boolean))];if(initials.length)assigned=db.query(`SELECT DISTINCT p.* FROM pendientes p JOIN pendientes_usuarios pu ON pu.id_pendiente=p.id_pendiente WHERE pu.iniciales_usuario IN (${sqlIn(initials)}) ORDER BY p.id_pendiente DESC LIMIT 100`,initials);const creatorClauses=[],creatorParams=[];if(initials.length){creatorClauses.push(`p.creado_por_iniciales IN (${sqlIn(initials)})`);creatorParams.push(...initials);}if(emails.length){creatorClauses.push(`p.creado_por_email IN (${sqlIn(emails)})`);creatorParams.push(...emails);}if(creatorClauses.length)created=db.query(`SELECT p.* FROM pendientes p WHERE (${creatorClauses.join(' OR ')}) ORDER BY p.id_pendiente DESC LIMIT 100`,creatorParams);const ph=sqlIn(ids);logistica=db.query(`SELECT * FROM logistica_produccion WHERE activo=1 AND (id_asesor IN (${ph}) OR id_supervisor IN (${ph}) OR created_by IN (${ph})) ORDER BY id_produccion DESC LIMIT 100`,[...ids,...ids,...ids]);instalaciones=db.query(`SELECT * FROM ins_fl WHERE activo=1 AND (id_asesor IN (${ph}) OR id_sup IN (${ph}) OR id_admin IN (${ph})) ORDER BY id_ins_fl DESC LIMIT 100`,[...ids,...ids,...ids]);}return{tablas:{logistica,instalaciones,tareas_asignadas:assigned,tareas_creadas:created},alcance:coreScope(userId,db)};}

  function dashboardPdfCapabilities(userId,candidateDb){return{ok:true,source:'lab-sqlite',general:true,individual:true,formatos:['GENERAL','INDIVIDUAL'],browser_pdf:true,server_file:false};}
  function dashboardPdfData(userId,query,candidateDb){const type=upper(query?.tipo||'GENERAL'),data={usuarios:dashboardUsers(userId,candidateDb).usuarios,kpis:dashboardKpis(userId,query,candidateDb).kpis,tablas:dashboardTables(userId,query,candidateDb).tablas,operacion:dashboardOperation(userId,query,candidateDb).tablas};return{ok:true,source:'lab-sqlite',tipo:type,data};}

  return Object.freeze({
    QUOTE_STATUSES,ACTIVE_QUOTE_STATUSES,EQUIPMENT_TYPES,coreScope,visibleUserIds,visibleCommercialUsers,
    clientCatalogs,listClients,getClient,createClient,updateClient,removeClient,listContacts,createContact,updateContact,removeContact,setPrincipalContact,
    quoteCatalogs,listQuotes,getQuote,kpisQuotes,quoteByStatus,quoteDashboardProjection,createQuote,updateQuote,removeQuote,updateQuoteStatus,updateQuoteAssignment,listHistory,
    listQuoteComments,addQuoteComment,updateQuoteComment,removeQuoteComment,listQuoteFiles,addQuoteFile,quoteFileAccess,removeQuoteFile,getInterest,setInterest,listInterests,
    prospectCatalogs,prospectCaptureCatalogs,prospectSources,prospectContacts,listProspects,prospectMap,getProspect,prospectKpis,createProspect,updateProspectStatus,linkProspectQuote,addProspectComment,prospectFileAccess,removeProspectFile,
    networkCatalogs,listNetworks,getNetwork,createNetwork,updateNetwork,removeNetwork,updateNetworkStatus,updateNetworkAssignment,updateNetworkQuotation,listNetworkFiles,uploadNetworkFiles,networkFileAccess,removeNetworkFile,listNetworkComments,createNetworkComment,updateNetworkComment,removeNetworkComment,addNetworkCommentAttachments,networkAttachmentAccess,removeNetworkAttachment,
    dashboardUsers,dashboardKpis,dashboardTables,dashboardOperation,dashboardPdfCapabilities,dashboardPdfData
  });
});
