(function initManttoLabCollectionsCorService(root,factory){
  const api=factory(root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.ManttoLabCollectionsCorService=api;
})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabCollectionsCorService(root){
  'use strict';

  function dbOr(candidate){const db=candidate||root?.ManttoLabDB;if(!db||typeof db.query!=='function')throw new Error('MANTTO_LAB_DB_REQUIRED');return db;}
  function httpError(status,message,code){const e=new Error(message);e.status=status;e.statusCode=status;e.code=code||'LAB_COLLECTIONS_COR_ERROR';return e;}
  function id(value,field='id'){const n=Number(value);if(!Number.isInteger(n)||n<=0)throw httpError(400,`${field} debe ser un entero positivo.`,'LAB_INVALID_ID');return n;}
  function actorId(actor){return id(actor?.id_SB||actor?.id||actor?.user_id,'usuario autenticado');}
  function text(value,max=500,fallback=null){const v=String(value??'').trim();return v?v.slice(0,max):fallback;}
  function money(value){const n=Number(value);return Number.isFinite(n)?n:0;}
  function bool(value){return value===true||value===1||value==='1'||String(value||'').toLowerCase()==='true';}
  function pageOf(query,defaultSize=30,max=100){const page=Math.max(1,parseInt(query?.page??query?.pagina??'1',10)||1);const size=Math.min(max,Math.max(1,parseInt(query?.page_size??query?.tamano_pagina??defaultSize,10)||defaultSize));return{page,size,offset:(page-1)*size};}
  function coreScope(userId,candidateDb){const svc=root?.ManttoLabScopeService;if(!svc)throw new Error('MANTTO_LAB_SCOPE_SERVICE_REQUIRED');return svc.resolveCorellian(Number(userId),dbOr(candidateDb));}
  function visibleIds(userId,candidateDb){const s=coreScope(userId,candidateDb);return s.llave_maestra?null:[...(s.usuarios_visibles||[])].map(Number).filter(n=>Number.isInteger(n)&&n>0);}
  function canSeeIndex(userId,row,candidateDb){if(!row)return false;const ids=visibleIds(userId,candidateDb);if(ids===null)return true;if(!ids.length)return false;return['vend','adm','sup','creado_por','actualizado_por'].some(k=>ids.includes(Number(row[k])));}
  function indexRows(userId,query,candidateDb){const db=dbOr(candidateDb),q=text(query?.search??query?.buscar)?.toUpperCase()||'',year=Number(query?.anio||0),status=text(query?.estatus)?.toUpperCase()||'';let rows=db.query('SELECT * FROM cobranza_indice_cor WHERE activo=1').filter(r=>canSeeIndex(userId,r,db));if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toUpperCase().includes(q)));if(Number.isInteger(year)&&year>0)rows=rows.filter(r=>Number(r.anio)===year);if(status)rows=rows.filter(r=>String(r.estatus||'').toUpperCase()===status);return rows.sort((a,b)=>Number(b.id_indice_cor)-Number(a.id_indice_cor));}
  function paginate(rows,query){const p=pageOf(query);const total=rows.length;return{rows:rows.slice(p.offset,p.offset+p.size),paginacion:{pagina:p.page,tamano_pagina:p.size,total:total,total_registros:total,total_paginas:total?Math.ceil(total/p.size):0}};}
  function listStatements(userId,query,candidateDb){const rows=indexRows(userId,query,candidateDb),p=paginate(rows,query);const totalUsd=rows.reduce((s,r)=>s+money(r.cobranza_usd),0),totalMxn=rows.reduce((s,r)=>s+money(r.cobranza_mxn),0);return{ok:true,source:'lab-sqlite',data:p.rows,resumen:{proyectos:rows.length,cobranza_usd:totalUsd,cobranza_mxn:totalMxn},paginacion:p.paginacion,alcance:coreScope(userId,candidateDb)};}
  function assertIndex(userId,rawId,candidateDb){const db=dbOr(candidateDb),rid=id(rawId,'id_indice_cor'),row=db.query('SELECT * FROM cobranza_indice_cor WHERE id_indice_cor=? AND activo=1',[rid])[0];if(!row||!canSeeIndex(userId,row,db))throw httpError(404,'Estado de cuenta no encontrado o fuera de alcance.','LAB_COLLECTIONS_COR_NOT_FOUND');return row;}
  function statementDetail(userId,rawId,candidateDb){const db=dbOr(candidateDb),row=assertIndex(userId,rawId,db),rid=Number(row.id_indice_cor),fuentes=db.query('SELECT * FROM cobranza_fuente_cor WHERE id_indice_cor=? AND activo=1 ORDER BY id_fuente_cor',[rid]),aditivas=db.query('SELECT * FROM cobranza_aditivas_cor WHERE id_indice_cor=? AND activo=1 ORDER BY id_aditiva_cor',[rid]),comentarios=db.query(`SELECT c.*,u.nombre,u.iniciales FROM cobranza_comentarios_cor c LEFT JOIN usuarios u ON u.id_SB=c.id_usuario WHERE c.id_indice_cor=? AND c.activo=1 ORDER BY c.fecha_creacion,c.id_comentario_cor`,[rid]),archivos=db.query('SELECT * FROM cobranza_archivos_cor WHERE id_indice_cor=? AND activo=1 ORDER BY id_archivo_cor',[rid]);return{ok:true,source:'lab-sqlite',data:{...row,fuentes,aditivas,comentarios,archivos},resumen:{fuentes:fuentes.length,total:fuentes.reduce((s,r)=>s+money(r.total),0),pagado:fuentes.reduce((s,r)=>s+money(r.pago_total),0),pendiente:fuentes.reduce((s,r)=>s+Math.max(0,money(r.total)-money(r.pago_total)),0)}};}
  function aditivaVisible(userId,row,candidateDb){if(!row)return false;try{assertIndex(userId,row.id_indice_cor,candidateDb);return true;}catch(_e){return false;}}
  function listAdditions(userId,query,candidateDb){const db=dbOr(candidateDb),q=text(query?.search??query?.buscar)?.toUpperCase()||'';let rows=db.query('SELECT * FROM cobranza_aditivas_cor WHERE activo=1').filter(r=>aditivaVisible(userId,r,db));if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toUpperCase().includes(q)));const p=paginate(rows.sort((a,b)=>Number(b.id_aditiva_cor)-Number(a.id_aditiva_cor)),query);return{ok:true,source:'lab-sqlite',data:p.rows,resumen:{registros:rows.length,monto_total:rows.reduce((s,r)=>s+money(r.monto_total),0),monto_pagado:rows.reduce((s,r)=>s+money(r.monto_pagado),0),pendiente_pago:rows.reduce((s,r)=>s+money(r.pendiente_pago),0)},catalogos:{monedas:['MXN','USD'],estatus_trabajos:[...new Set(rows.map(r=>r.estatus_trabajos).filter(Boolean))],estatus_cobranza:[...new Set(rows.map(r=>r.estatus_cobranza).filter(Boolean))]},paginacion:p.paginacion,alcance:coreScope(userId,db)};}
  function getAddition(userId,rawId,candidateDb){const db=dbOr(candidateDb),rid=id(rawId,'id_aditiva_cor'),row=db.query('SELECT * FROM cobranza_aditivas_cor WHERE id_aditiva_cor=? AND activo=1',[rid])[0];if(!row||!aditivaVisible(userId,row,db))throw httpError(404,'Aditiva no encontrada o fuera de alcance.','LAB_COLLECTIONS_COR_NOT_FOUND');return{ok:true,source:'lab-sqlite',data:row};}
  function normalizedAddition(body,existing){const b={...(existing||{}),...(body||{})};const subtotal=money(b.monto_subtotal),ivaPct=Number.isFinite(Number(b.iva_pct))?Number(b.iva_pct):0.16,iva=Object.prototype.hasOwnProperty.call(b,'monto_iva')?money(b.monto_iva):subtotal*ivaPct,total=Object.prototype.hasOwnProperty.call(b,'monto_total')?money(b.monto_total):subtotal+iva,pagado=money(b.monto_pagado);return{id_indice_cor:id(b.id_indice_cor,'id_indice_cor'),anio_cot:Number(b.anio_cot)||new Date().getFullYear(),departamento:text(b.departamento,120),categoria:text(b.categoria,120),fecha_cot:text(b.fecha_cot,20),firma_cot:text(b.firma_cot,120),no_cot:text(b.no_cot,120),ov:text(b.ov,120),factura:text(b.factura,120),estatus_trabajos:text(b.estatus_trabajos,120),estatus_cobranza:text(b.estatus_cobranza,120),sup:text(b.sup,120),pp_ns:text(b.pp_ns,120),proyecto:text(b.proyecto,220),equipo:text(b.equipo,120),descripcion:text(b.descripcion,2000),comentario_fuente:text(b.comentario_fuente,2000),monto_subtotal:subtotal,iva_pct:ivaPct,monto_iva:iva,monto_total:total,gasto_subtotal:money(b.gasto_subtotal),oc:text(b.oc,120),diferencia:money(b.diferencia),utilidad_real_pct:money(b.utilidad_real_pct),monto_pagado:pagado,pagado_sin_iva:money(b.pagado_sin_iva),pendiente_pago:Object.prototype.hasOwnProperty.call(b,'pendiente_pago')?money(b.pendiente_pago):Math.max(0,total-pagado),fecha_pago:text(b.fecha_pago,20),semana_pago:text(b.semana_pago,30),moneda:text(b.moneda,10,'MXN'),gasto_ejercido:text(b.gasto_ejercido,120)};}
  function createAddition(userId,body,actor,candidateDb){const db=dbOr(candidateDb),uid=actorId(actor),b=normalizedAddition(body);const index=assertIndex(userId,b.id_indice_cor,db);if(!b.proyecto)b.proyecto=index.proyecto;const r=db.run(`INSERT INTO cobranza_aditivas_cor(id_indice_cor,anio_cot,departamento,categoria,fecha_cot,firma_cot,no_cot,ov,factura,estatus_trabajos,estatus_cobranza,sup,pp_ns,proyecto,equipo,descripcion,comentario_fuente,monto_subtotal,iva_pct,monto_iva,monto_total,gasto_subtotal,oc,diferencia,utilidad_real_pct,monto_pagado,pagado_sin_iva,pendiente_pago,fecha_pago,semana_pago,moneda,gasto_ejercido,activo,creado_por,actualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)`,[b.id_indice_cor,b.anio_cot,b.departamento,b.categoria,b.fecha_cot,b.firma_cot,b.no_cot,b.ov,b.factura,b.estatus_trabajos,b.estatus_cobranza,b.sup,b.pp_ns,b.proyecto,b.equipo,b.descripcion,b.comentario_fuente,b.monto_subtotal,b.iva_pct,b.monto_iva,b.monto_total,b.gasto_subtotal,b.oc,b.diferencia,b.utilidad_real_pct,b.monto_pagado,b.pagado_sin_iva,b.pendiente_pago,b.fecha_pago,b.semana_pago,b.moneda,b.gasto_ejercido,uid,uid]);return getAddition(userId,r.lastInsertRowId,db);}
  function updateAddition(userId,rawId,body,actor,candidateDb){const db=dbOr(candidateDb),rid=id(rawId,'id_aditiva_cor'),uid=actorId(actor),old=getAddition(userId,rid,db).data,b=normalizedAddition(body,old);assertIndex(userId,b.id_indice_cor,db);db.run(`UPDATE cobranza_aditivas_cor SET id_indice_cor=?,anio_cot=?,departamento=?,categoria=?,fecha_cot=?,firma_cot=?,no_cot=?,ov=?,factura=?,estatus_trabajos=?,estatus_cobranza=?,sup=?,pp_ns=?,proyecto=?,equipo=?,descripcion=?,comentario_fuente=?,monto_subtotal=?,iva_pct=?,monto_iva=?,monto_total=?,gasto_subtotal=?,oc=?,diferencia=?,utilidad_real_pct=?,monto_pagado=?,pagado_sin_iva=?,pendiente_pago=?,fecha_pago=?,semana_pago=?,moneda=?,gasto_ejercido=?,actualizado_por=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id_aditiva_cor=?`,[b.id_indice_cor,b.anio_cot,b.departamento,b.categoria,b.fecha_cot,b.firma_cot,b.no_cot,b.ov,b.factura,b.estatus_trabajos,b.estatus_cobranza,b.sup,b.pp_ns,b.proyecto,b.equipo,b.descripcion,b.comentario_fuente,b.monto_subtotal,b.iva_pct,b.monto_iva,b.monto_total,b.gasto_subtotal,b.oc,b.diferencia,b.utilidad_real_pct,b.monto_pagado,b.pagado_sin_iva,b.pendiente_pago,b.fecha_pago,b.semana_pago,b.moneda,b.gasto_ejercido,uid,rid]);return getAddition(userId,rid,db);}
  function contractualDebts(userId,query,candidateDb){const db=dbOr(candidateDb),visible=indexRows(userId,{},db),ids=visible.map(r=>Number(r.id_indice_cor));if(!ids.length)return{ok:true,source:'lab-sqlite',data:[],resumen:{total:0,pagado:0,adeudo:0}};let rows=db.query(`SELECT f.*,i.proyecto AS proyecto_indice,i.vend,i.adm,i.sup FROM cobranza_fuente_cor f JOIN cobranza_indice_cor i ON i.id_indice_cor=f.id_indice_cor WHERE f.activo=1 AND i.activo=1 AND f.id_indice_cor IN (${ids.map(()=>'?').join(',')})`,ids).map(r=>({...r,adeudo_calculado:Math.max(0,money(r.total)-money(r.pago_total))}));const q=text(query?.search??query?.buscar)?.toUpperCase()||'';if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toUpperCase().includes(q)));return{ok:true,source:'lab-sqlite',data:rows,resumen:{total:rows.reduce((s,r)=>s+money(r.total),0),pagado:rows.reduce((s,r)=>s+money(r.pago_total),0),adeudo:rows.reduce((s,r)=>s+money(r.adeudo_calculado),0)},alcance:coreScope(userId,db)};}

  return Object.freeze({coreScope,visibleIds,listStatements,statementDetail,listAdditions,getAddition,createAddition,updateAddition,contractualDebts});
});
