(function initManttoLabLogisticsService(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ManttoLabLogisticsService=api;})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabLogisticsService(root){
'use strict';
function dbOr(db){const out=db||root?.ManttoLabDB;if(!out)throw new Error('MANTTO_LAB_DB_REQUIRED');return out;}function id(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:null;}function text(v,max=500){const s=String(v??'').trim();return max?s.slice(0,max):s;}function actorId(a){return id(a?.id_SB)||id(a?.id_usuario)||null;}function err(status,message,code){const e=new Error(message);e.status=status;e.code=code;return e;}function now(){return new Date().toISOString();}
function coreScope(userId,db){return root?.ManttoLabScopeService?.resolveCorellian?.(userId,db)||{llave_maestra:false,usuarios_visibles:[]};}
function scopeSql(userId,alias,candidateDb){const db=dbOr(candidateDb),uid=id(userId);if(!uid)return{sql:'1=0',params:[]};const s=coreScope(uid,db);if(s.llave_maestra)return{sql:'1=1',params:[]};const ids=Array.isArray(s.usuarios_visibles)?s.usuarios_visibles.map(Number).filter(Boolean):[uid];if(!ids.includes(uid))ids.push(uid);const ph=ids.map(()=>'?').join(',');return{sql:`(${alias}.id_asesor IN (${ph}) OR ${alias}.id_supervisor IN (${ph}) OR ${alias}.created_by IN (${ph}) OR ${alias}.updated_by IN (${ph}))`,params:[...ids,...ids,...ids,...ids]};}
function rowById(userId,rowId,candidateDb){const db=dbOr(candidateDb),s=scopeSql(userId,'l',db),rid=id(rowId),row=db.query(`SELECT l.*,u1.nombre AS asesor_nombre,u2.nombre AS supervisor_nombre,c.articulo AS estatus_produccion_nombre FROM logistica_produccion l LEFT JOIN usuarios u1 ON u1.id_SB=l.id_asesor LEFT JOIN usuarios u2 ON u2.id_SB=l.id_supervisor LEFT JOIN catalogo_general c ON c.id_catalogo=l.id_estatus_produccion WHERE l.id_produccion=? AND l.activo=1 AND ${s.sql} LIMIT 1`,[rid,...s.params])[0];if(!row)throw err(404,'Registro de Logística no encontrado o fuera de alcance.','LAB_LOGISTICS_NOT_FOUND');return row;}
function list(userId,query,candidateDb){const db=dbOr(candidateDb),s=scopeSql(userId,'l',db),q=text(query?.q||query?.search,120),status=text(query?.estatus||query?.estatus_logistica,120),params=[...s.params],clauses=['l.activo=1',s.sql];if(q){const like=`%${q}%`;clauses.push('(l.proyecto LIKE ? OR l.ppns LIKE ? OR l.comentario LIKE ?)');params.push(like,like,like);}if(status){clauses.push('UPPER(COALESCE(l.estatus_logistica,\'\'))=UPPER(?)');params.push(status);}const rows=db.query(`SELECT l.*,u1.nombre AS asesor_nombre,u2.nombre AS supervisor_nombre,c.articulo AS estatus_produccion_nombre FROM logistica_produccion l LEFT JOIN usuarios u1 ON u1.id_SB=l.id_asesor LEFT JOIN usuarios u2 ON u2.id_SB=l.id_supervisor LEFT JOIN catalogo_general c ON c.id_catalogo=l.id_estatus_produccion WHERE ${clauses.join(' AND ')} ORDER BY l.anio_registro DESC,l.semana_registro DESC,l.id_produccion DESC`,params);return{data:rows,registros:rows,total:rows.length};}
function detail(userId,rowId,candidateDb){const db=dbOr(candidateDb),row=rowById(userId,rowId,db),files=db.query('SELECT * FROM logistica_produccion_archivos WHERE id_produccion=? AND activo=1 ORDER BY tipo_archivo,numero_archivo',[row.id_produccion]).map(f=>({...f,access_endpoint:`/api/logistica/${row.id_produccion}/archivos/${f.id_archivo}/acceso`}));return{...row,archivos:files};}
function currentIso(){const d=new Date(),tmp=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));tmp.setUTCDate(tmp.getUTCDate()+4-(tmp.getUTCDay()||7));const y=new Date(Date.UTC(tmp.getUTCFullYear(),0,1)),week=Math.ceil((((tmp-y)/86400000)+1)/7);return{year:tmp.getUTCFullYear(),week};}
function create(userId,body,actor,candidateDb){const db=dbOr(candidateDb),aid=actorId(actor)||id(userId),iso=currentIso(),project=text(body?.proyecto,255),ppns=text(body?.ppns||body?.id_ppns,255);if(!project&&!ppns)throw err(400,'proyecto o ppns es obligatorio.','LAB_LOGISTICS_REQUIRED_FIELD');const r=db.run(`INSERT INTO logistica_produccion(modo_registro,ppns,proyecto,id_cotizacion_venta,id_asesor,id_supervisor,fecha_pvo,fecha_pvo_fl,fecha_cubos,estatus_logistica,id_estatus_produccion,comentario,fecha_envio_docs_fabrica,fecha_envio_pago_fabrica,semana_registro,anio_registro,origen_registro,activo,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'GESTOR_LAB\',1,?,?)`,[text(body?.modo_registro||'MANUAL',50),ppns||null,project||null,id(body?.id_cotizacion_venta),id(body?.id_asesor)||aid,id(body?.id_supervisor),text(body?.fecha_pvo,40)||null,text(body?.fecha_pvo_fl,40)||null,text(body?.fecha_cubos,40)||null,text(body?.estatus_logistica,150)||null,id(body?.id_estatus_produccion),text(body?.comentario,5000)||null,text(body?.fecha_envio_docs_fabrica,40)||null,text(body?.fecha_envio_pago_fabrica,40)||null,Number(body?.semana_registro)||iso.week,Number(body?.anio_registro)||iso.year,aid,aid],{persist:false});return detail(userId,r.lastInsertRowId,db);}
function update(userId,rowId,body,actor,candidateDb){const db=dbOr(candidateDb),row=rowById(userId,rowId,db),allowed=['modo_registro','ppns','proyecto','id_cotizacion_venta','id_asesor','id_supervisor','fecha_pvo','fecha_pvo_fl','fecha_cubos','estatus_logistica','id_estatus_produccion','comentario','fecha_envio_docs_fabrica','fecha_envio_pago_fabrica','semana_registro','anio_registro'],sets=[],params=[];for(const key of allowed){if(!Object.prototype.hasOwnProperty.call(body||{},key))continue;sets.push(`${key}=?`);params.push(['id_cotizacion_venta','id_asesor','id_supervisor','id_estatus_produccion'].includes(key)?id(body[key]):(['semana_registro','anio_registro'].includes(key)?Number(body[key]):(body[key]===null?null:text(body[key],key==='comentario'?5000:255))));}sets.push('updated_by=?','updated_at=CURRENT_TIMESTAMP');params.push(actorId(actor)||id(userId));db.run(`UPDATE logistica_produccion SET ${sets.join(',')} WHERE id_produccion=?`,[...params,row.id_produccion],{persist:false});return detail(userId,row.id_produccion,db);}
function remove(userId,rowId,actor,candidateDb){const db=dbOr(candidateDb),row=rowById(userId,rowId,db);db.run('UPDATE logistica_produccion SET activo=0,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id_produccion=?',[actorId(actor)||id(userId),row.id_produccion],{persist:false});return{removed:true,id_produccion:Number(row.id_produccion)};}
function statuses(candidateDb){const db=dbOr(candidateDb);return db.query("SELECT id_catalogo,articulo,descripcion,orden FROM catalogo_general WHERE activo=1 AND UPPER(area) LIKE '%LOGIST%' ORDER BY orden,id_catalogo");}
function pieces(userId,query,candidateDb){const rows=list(userId,query,candidateDb).data,needle=text(query?.search||query?.q,100).toUpperCase();const vals=[...new Set(rows.flatMap(r=>[r.ppns,r.proyecto]).filter(Boolean))].filter(v=>!needle||String(v).toUpperCase().includes(needle)).slice(0,50);return{data:vals.map((v,i)=>({id:i+1,nombre:v,valor:v})),total:vals.length};}
function weeklySummary(userId,query,candidateDb){const rows=list(userId,query,candidateDb).data;const week=Number(query?.week||query?.semana||0),year=Number(query?.year||query?.anio||0);const filtered=rows.filter(r=>(!week||Number(r.semana_registro)===week)&&(!year||Number(r.anio_registro)===year));const by={};filtered.forEach(r=>{const key=r.estatus_logistica||r.estatus_produccion_nombre||'SIN ESTATUS';by[key]=(by[key]||0)+1;});return{ok:true,source:'lab-sqlite',week:week||null,year:year||null,total:filtered.length,pipeline:Object.entries(by).map(([estatus,total])=>({estatus,total})),data:filtered};}
async function addFile(userId,rowId,body,actor,candidateDb){const db=dbOr(candidateDb),row=rowById(userId,rowId,db),blob=root?.ManttoLabBlobStore;if(!blob)throw new Error('MANTTO_LAB_BLOB_STORE_REQUIRED');const file=body?.file||body?.archivo;if(!blob.isFileLike(file))throw err(400,'Selecciona un archivo válido.','LAB_FILE_REQUIRED');const type=String(body?.tipo_archivo||'GM').toUpperCase();if(!['CPVO','GM'].includes(type))throw err(400,'tipo_archivo debe ser CPVO o GM.','LAB_LOGISTICS_FILE_TYPE');const max=type==='CPVO'?2:10;let slot=id(body?.numero_archivo);if(!slot){for(let n=1;n<=max;n++){if(!db.scalar('SELECT COUNT(*) FROM logistica_produccion_archivos WHERE id_produccion=? AND tipo_archivo=? AND numero_archivo=? AND activo=1',[row.id_produccion,type,n])){slot=n;break;}}}if(!slot||slot>max)throw err(409,'No hay espacio disponible para ese tipo de archivo.','LAB_LOGISTICS_FILE_SLOT');const old=db.query('SELECT * FROM logistica_produccion_archivos WHERE id_produccion=? AND tipo_archivo=? AND numero_archivo=? AND activo=1 LIMIT 1',[row.id_produccion,type,slot])[0];if(old){db.run('UPDATE logistica_produccion_archivos SET activo=0,eliminado_por=?,eliminado_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[actorId(actor)||id(userId),old.id_archivo],{persist:false});if(old.storage_blob_name)await blob.remove(old.storage_blob_name);}const stored=await blob.put(file,{prefix:`logistics/${row.id_produccion}/${type}`});const r=await db.run(`INSERT INTO logistica_produccion_archivos(id_produccion,tipo_archivo,numero_archivo,nombre_archivo,nombre_original,extension,mime_type,tamanio_bytes,storage_provider,storage_container,storage_blob_name,storage_url,origen_archivo,id_usuario,activo) VALUES(?,?,?,?,?,?,?,?,\'LAB_INDEXEDDB\',\'mantto_lab_dgb\',?,NULL,\'NUEVO\',?,1)`,[row.id_produccion,type,slot,stored.name,stored.name,(stored.name.split('.').pop()||'').slice(0,20),stored.type,stored.size,stored.key,actorId(actor)||id(userId)],{persist:false});return db.query('SELECT * FROM logistica_produccion_archivos WHERE id_archivo=?',[r.lastInsertRowId])[0];}
function fileRow(userId,rowId,fileId,candidateDb){const db=dbOr(candidateDb),row=rowById(userId,rowId,db),file=db.query('SELECT * FROM logistica_produccion_archivos WHERE id_archivo=? AND id_produccion=? AND activo=1 LIMIT 1',[id(fileId),row.id_produccion])[0];if(!file)throw err(404,'Archivo de Logística no encontrado.','LAB_LOGISTICS_FILE_NOT_FOUND');return file;}
async function fileAccess(userId,rowId,fileId,candidateDb){const file=fileRow(userId,rowId,fileId,candidateDb),data=await root.ManttoLabBlobStore.accessUrl(file.storage_blob_name);if(!data)throw err(404,'Contenido local no encontrado.','LAB_LOCAL_BLOB_NOT_FOUND');return{...data,id_archivo:Number(file.id_archivo)};}
async function removeFile(userId,rowId,fileId,actor,candidateDb){const db=dbOr(candidateDb),file=fileRow(userId,rowId,fileId,db);db.run('UPDATE logistica_produccion_archivos SET activo=0,eliminado_por=?,eliminado_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id_archivo=?',[actorId(actor)||id(userId),file.id_archivo],{persist:false});if(file.storage_blob_name)await root.ManttoLabBlobStore.remove(file.storage_blob_name);return{removed:true,id_archivo:Number(file.id_archivo)};}
function config(candidateDb){return{source:'LAB_SQLITE',google_sheets:false,external_sync:false,columns:['ppns','proyecto','estatus_logistica','fecha_pvo','fecha_pvo_fl','fecha_cubos','comentario'],estatus_produccion:statuses(candidateDb)};}
return Object.freeze({scopeSql,list,detail,create,update,remove,statuses,pieces,weeklySummary,addFile,fileAccess,removeFile,config});
});
