(function initManttoLabBackupService(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ManttoLabBackupService=api;})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabBackupService(root){
'use strict';
const FORMAT='MANTTO_LAB_DGB_BACKUP';
const FORMAT_VERSION=1;
const LINEAGE='LAB_DGB_V2';
const REQUIRED_USER_VERSION=10;
function dbOr(candidate){const db=candidate||root?.ManttoLabDB;if(!db||typeof db.exportBytes!=='function'||typeof db.replaceWithBytes!=='function')throw new Error('MANTTO_LAB_DB_REQUIRED');return db;}
function blobsOr(candidate){const blobs=candidate||root?.ManttoLabBlobStore;if(!blobs||typeof blobs.exportAll!=='function'||typeof blobs.importAll!=='function')throw new Error('MANTTO_LAB_BLOB_STORE_REQUIRED');return blobs;}
function bytesToBase64(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input||[]);if(typeof root?.btoa==='function'){let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return root.btoa(binary);}if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64');throw new Error('LAB_BASE64_ENCODER_UNAVAILABLE');}
function base64ToBytes(value){const text=String(value||'').trim();if(typeof root?.atob==='function'){const binary=root.atob(text);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);return bytes;}if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(text,'base64'));throw new Error('LAB_BASE64_DECODER_UNAVAILABLE');}
async function sha256Hex(bytes){const subtle=root?.crypto?.subtle;if(!subtle?.digest)return null;const source=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes||[]);const digest=await subtle.digest('SHA-256',source);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}
function parseEnvelope(value){if(value&&typeof value==='object'&&!ArrayBuffer.isView(value))return value;if(typeof value!=='string')throw Object.assign(new Error('Respaldo LAB inválido.'),{code:'LAB_BACKUP_INVALID'});try{return JSON.parse(value);}catch(_error){throw Object.assign(new Error('El respaldo LAB no contiene JSON válido.'),{code:'LAB_BACKUP_JSON_INVALID'});}}
async function validateEnvelope(value,options){const cfg=options||{},envelope=parseEnvelope(value);if(envelope.format!==FORMAT)throw Object.assign(new Error('Formato de respaldo LAB no reconocido.'),{code:'LAB_BACKUP_FORMAT_INVALID'});if(Number(envelope.formatVersion)!==FORMAT_VERSION)throw Object.assign(new Error('Versión de respaldo LAB no compatible.'),{code:'LAB_BACKUP_VERSION_INVALID'});if(envelope.lineage!==LINEAGE)throw Object.assign(new Error('El respaldo pertenece a otra línea de laboratorio.'),{code:'LAB_BACKUP_LINEAGE_MISMATCH'});if(Number(envelope.userVersion)!==REQUIRED_USER_VERSION)throw Object.assign(new Error(`El respaldo debe pertenecer a user_version ${REQUIRED_USER_VERSION}.`),{code:'LAB_BACKUP_USER_VERSION_MISMATCH'});if(!envelope.database?.base64)throw Object.assign(new Error('El respaldo no contiene la base SQLite.'),{code:'LAB_BACKUP_DATABASE_MISSING'});const bytes=base64ToBytes(envelope.database.base64);if(envelope.database.bytes!==undefined&&Number(envelope.database.bytes)!==bytes.length)throw Object.assign(new Error('El tamaño declarado de SQLite no coincide con el respaldo.'),{code:'LAB_BACKUP_DATABASE_SIZE_MISMATCH'});const db=dbOr(cfg.db);const inspection=await db.inspectBytes(bytes,{expectedUserVersion:REQUIRED_USER_VERSION});const hash=await sha256Hex(bytes);if(envelope.database.sha256&&hash&&String(envelope.database.sha256).toLowerCase()!==hash)throw Object.assign(new Error('SHA-256 de la base SQLite no coincide.'),{code:'LAB_BACKUP_DATABASE_HASH_MISMATCH'});const blobStore=blobsOr(cfg.blobStore);const blobValidation=blobStore.validateImportEntries(Array.isArray(envelope.blobs)?envelope.blobs:[]);return{envelope,bytes,inspection,blobValidation,sha256:hash};}
async function exportEnvelope(options){const cfg=options||{},db=dbOr(cfg.db),blobStore=blobsOr(cfg.blobStore);const bytes=db.exportBytes(),stats=db.databaseStatistics(),blobs=await blobStore.exportAll(),hash=await sha256Hex(bytes);return{format:FORMAT,formatVersion:FORMAT_VERSION,lineage:LINEAGE,userVersion:Number(stats.sqliteUserVersion||0),exportedAt:new Date().toISOString(),database:{encoding:'base64',bytes:bytes.length,sha256:hash,base64:bytesToBase64(bytes)},blobs,metadata:{tables:Number(stats.tables||0),foreignKeyViolations:Number(stats.foreignKeyViolations||0),blobCount:blobs.length,productionConnectionsAllowed:false}};}
async function exportJson(options){return JSON.stringify(await exportEnvelope(options),null,2);}
async function summary(options){const cfg=options||{},db=dbOr(cfg.db),blobStore=blobsOr(cfg.blobStore),stats=db.databaseStatistics(),list=await blobStore.list();return{format:FORMAT,formatVersion:FORMAT_VERSION,lineage:LINEAGE,userVersion:Number(stats.sqliteUserVersion||0),tables:Number(stats.tables||0),foreignKeyViolations:Number(stats.foreignKeyViolations||0),blobCount:list.length,blobBytes:list.reduce((sum,row)=>sum+Number(row.size||0),0),database:db.getStatus?.()||null};}
async function importEnvelope(value,options){const cfg=options||{},db=dbOr(cfg.db),blobStore=blobsOr(cfg.blobStore),validated=await validateEnvelope(value,{db,blobStore});const previousDb=db.exportBytes(),previousBlobs=await blobStore.exportAll();try{await db.replaceWithBytes(validated.bytes,{expectedUserVersion:REQUIRED_USER_VERSION,reason:'phase10-backup-import'});await blobStore.importAll(validated.envelope.blobs||[],{replace:true});if(root?.document&&typeof root.CustomEvent==='function')root.document.dispatchEvent(new root.CustomEvent('mantto:lab-backup-imported',{detail:{userVersion:REQUIRED_USER_VERSION,blobs:validated.blobValidation.count}}));return{ok:true,userVersion:REQUIRED_USER_VERSION,database:validated.inspection,blobs:validated.blobValidation.count};}catch(error){try{await db.replaceWithBytes(previousDb,{reason:'phase10-backup-rollback'});}catch(_dbRollback){}try{await blobStore.importAll(previousBlobs,{replace:true});}catch(_blobRollback){}throw error;}}
async function download(options){const json=await exportJson(options);const BlobCtor=root?.Blob||(typeof Blob!=='undefined'?Blob:null);if(!BlobCtor||!root?.URL?.createObjectURL||!root?.document)throw new Error('LAB_BACKUP_DOWNLOAD_UNAVAILABLE');const blob=new BlobCtor([json],{type:'application/json'}),url=root.URL.createObjectURL(blob),a=root.document.createElement('a'),stamp=new Date().toISOString().replace(/[:.]/g,'-');a.href=url;a.download=`MANTTO_LAB_DGB_BACKUP_${stamp}.json`;a.style.display='none';root.document.body.appendChild(a);a.click();a.remove();setTimeout(()=>root.URL.revokeObjectURL(url),0);return{fileName:a.download,bytes:blob.size};}
return Object.freeze({FORMAT,FORMAT_VERSION,LINEAGE,REQUIRED_USER_VERSION,summary,exportEnvelope,exportJson,validateEnvelope,importEnvelope,download});
});
