(function initManttoLabCriticalsService(root,factory){
  const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ManttoLabCriticalsService=api;
})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabCriticalsService(root){
  'use strict';
  function dbOr(db){return db||root.ManttoLabDB;}
  function txt(v){return String(v==null?'':v).trim();}
  function upper(v){return txt(v).toUpperCase();}
  function day(v){const m=txt(v).match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1]:null;}
  function date(v){const d=day(v);if(!d)return null;const x=new Date(d+'T12:00:00');return Number.isNaN(x.getTime())?null:x;}
  function now(){return new Date();}
  function daysBetween(a,b){return Math.max(0,Math.floor((b.getTime()-a.getTime())/86400000));}
  function positive(v,fallback,min,max){const n=parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
  function paginate(rows,q,defaultSize){const page=positive(q?.page,1,1,100000),pageSize=positive(q?.page_size||q?.pageSize,defaultSize||25,1,5000),start=(page-1)*pageSize;return{data:rows.slice(start,start+pageSize),pagination:{page,page_size:pageSize,total:rows.length}};}
  function prefs(userId,db){const row=dbOr(db).query('SELECT criticos_fallas,criticos_periodo FROM usuarios WHERE id_SB=? LIMIT 1',[Number(userId)])[0]||{};return{fallas:positive(row.criticos_fallas,3,1,9999),periodo:positive(row.criticos_periodo,35,1,3650)};}
  function ticketMap(userId,db){const rows=root.ManttoLabOperationService.visibleTickets(userId,db),map=new Map();rows.forEach(t=>{const code=txt(t.codigo_equipo||t.equipo);if(!map.has(code))map.set(code,[]);map.get(code).push(t);});return map;}
  function periodTickets(tickets,days,reference){const end=reference||now(),cut=new Date(end.getTime()-days*86400000);return(tickets||[]).filter(t=>{const d=date(t.fecha_reporte);return d&&d<=end&&d>=cut;});}
  function blt(tickets){return(tickets||[]).filter(t=>upper(t.responsabilidad)==='BLT');}
  function client(tickets){return(tickets||[]).filter(t=>upper(t.responsabilidad)==='CLIENTE');}
  function latestDate(tickets){return(tickets||[]).map(t=>day(t.fecha_reporte)).filter(Boolean).sort().reverse()[0]||null;}
  function mtbc(tickets,periodDays,equipmentCount){const failures=blt(tickets).length;return failures>0?Math.round((Number(periodDays)*Math.max(1,Number(equipmentCount)||1)/failures)*10)/10:null;}
  function currentYearDays(){const n=now(),start=new Date(n.getFullYear(),0,1,12);return Math.max(1,daysBetween(start,n)+1);}
  function ticketsYear(tickets){const n=now(),y=n.getFullYear();return(tickets||[]).filter(t=>{const d=date(t.fecha_reporte);return d&&d<=n&&d.getFullYear()===y;});}
  function equipmentRows(userId,query,candidateDb){const db=dbOr(candidateDb),q=query||{},p=prefs(userId,db),days=positive(q.dias||q.periodo,p.periodo,1,3650),minFailures=positive(q.min_fallas||q.minFallas||q.fallas,p.fallas,1,9999),zone=upper(q.zona),project=upper(q.proyecto),search=upper(q.search||q.buscar),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),today=now();const rows=[];
    portfolio.forEach(eq=>{const code=txt(eq.numero_equipo),tickets=map.get(code)||[],period=periodTickets(tickets,days,today),periodBlt=blt(period);if(periodBlt.length<minFailures)return;const y=ticketsYear(tickets),u365=periodTickets(tickets,365,today),periodClient=client(period),outsideBlt=blt(tickets).length-periodBlt.length,outsideClient=client(tickets).length-periodClient.length;const row={zona:eq.zona_oficial||eq.zona_operativa,proyecto:eq.proyecto,proyecto_nombre:eq.nombre_publico||eq.proyecto_cc_x_port||eq.proyecto,codigo_equipo:code,numero_equipo:code,identificacion_sitio:eq.identificacion_sitio,estatus_servicio:eq.estatus_servicio,llamadas_anio:y.length,calls_anio:y.length,fallas_blt_periodo:periodBlt.length,blt_fuera_periodo:Math.max(0,outsideBlt),ultima_blt:latestDate(blt(tickets)),resp_cliente_periodo:periodClient.length,cliente_fuera_periodo:Math.max(0,outsideClient),ultima_cliente:latestDate(client(tickets)),mtbc_anio_actual:mtbc(ticketsYear(tickets),currentYearDays(),1),mtbc_u365:mtbc(u365,365,1),tickets_periodo:period.length};if(zone&&!upper(row.zona).includes(zone))return;if(project&&!upper(row.proyecto).includes(project)&&!upper(row.proyecto_nombre).includes(project))return;if(search&&!upper([row.codigo_equipo,row.proyecto,row.proyecto_nombre,row.identificacion_sitio].join(' ')).includes(search))return;rows.push(row);});
    rows.sort((a,b)=>b.fallas_blt_periodo-a.fallas_blt_periodo||txt(a.codigo_equipo).localeCompare(txt(b.codigo_equipo)));return{days,minFailures,rows};}
  function equiposCriticos(userId,query,db){const calc=equipmentRows(userId,query,db),page=paginate(calc.rows,query,25);return{ok:true,source:'lab-sqlite',criterio:{dias:calc.days,min_fallas:calc.minFailures},...page};}
  function equipoTickets(userId,code,query,db){const visible=root.ManttoLabOperationService.activeInServicePortfolio(userId,db).some(e=>txt(e.numero_equipo)===txt(code));if(!visible)return null;let rows=(ticketMap(userId,db).get(txt(code))||[]).slice();const days=positive(query?.dias,3650,1,3650),responsibility=upper(query?.responsabilidad);rows=periodTickets(rows,days,now());if(responsibility)rows=rows.filter(t=>upper(t.responsabilidad)===responsibility);return rows;}
  function projectRows(userId,query,candidateDb){const db=dbOr(candidateDb),q=query||{},days=positive(q.dias,35,1,3650),minFailures=positive(q.min_fallas,5,1,9999),minEq=positive(q.min_fallas_equipo,3,1,9999),zone=upper(q.zona),projectNeedle=upper(q.proyecto),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),by=new Map();portfolio.forEach(eq=>{const key=txt(eq.proyecto);if(!key)return;if(!by.has(key))by.set(key,{project:key,equipment:[]});by.get(key).equipment.push(eq);});const rows=[];for(const item of by.values()){const allTickets=item.equipment.flatMap(eq=>map.get(txt(eq.numero_equipo))||[]),period=periodTickets(allTickets,days,now()),periodBlt=blt(period);if(periodBlt.length<minFailures)continue;const criticalEquipment=item.equipment.filter(eq=>blt(periodTickets(map.get(txt(eq.numero_equipo))||[],days,now())).length>=minEq);const year=ticketsYear(allTickets),u365=periodTickets(allTickets,365,now()),first=item.equipment[0],zones=[...new Set(item.equipment.map(e=>e.zona_oficial||e.zona_operativa).filter(Boolean))],supervisors=[...new Set(item.equipment.map(e=>e.supervisor_zona).filter(Boolean))];const row={proyecto:item.project,proyecto_codigo:item.project,proyecto_nombre:first.nombre_publico||first.proyecto_cc_x_port||item.project,ciudad:first.ciudad,estado:first.estado,zona:zones.join(' / '),zona_oficial:zones.join(' / '),supervisor:supervisors.join(' / '),equipos_activos:item.equipment.length,equipos:item.equipment.length,fallas_blt_periodo:periodBlt.length,equipos_con_falla:new Set(periodBlt.map(t=>txt(t.codigo_equipo))).size,equipos_criticos:criticalEquipment.length,ultima_blt:latestDate(blt(allTickets)),mtbc_anio_actual:mtbc(year,currentYearDays(),item.equipment.length),mtbc_u365:mtbc(u365,365,item.equipment.length)};if(zone&&!upper(row.zona).includes(zone))continue;if(projectNeedle&&!upper(row.proyecto).includes(projectNeedle)&&!upper(row.proyecto_nombre).includes(projectNeedle))continue;rows.push(row);}rows.sort((a,b)=>b.fallas_blt_periodo-a.fallas_blt_periodo||txt(a.proyecto).localeCompare(txt(b.proyecto)));return{days,minFailures,minEq,rows};}
  function proyectosCriticos(userId,query,db){const calc=projectRows(userId,query,db),page=paginate(calc.rows,query,25);return{ok:true,source:'lab-sqlite',criterio:{dias:calc.days,min_fallas:calc.minFailures,min_fallas_equipo:calc.minEq},...page};}
  function proyectoTickets(userId,project,query,db){const needle=upper(project),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db).filter(e=>upper(e.proyecto)===needle||upper(e.nombre_publico)===needle||upper(e.proyecto_cc_x_port)===needle);if(!portfolio.length)return null;const codes=new Set(portfolio.map(e=>txt(e.numero_equipo)));let rows=root.ManttoLabOperationService.visibleTickets(userId,db).filter(t=>codes.has(txt(t.codigo_equipo)));const days=positive(query?.dias,3650,1,3650);return periodTickets(rows,days,now());}
  function mtbcEquipos(userId,query,candidateDb){const db=dbOr(candidateDb),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),rows=portfolio.map(eq=>{const t=map.get(txt(eq.numero_equipo))||[];return{codigo_equipo:eq.numero_equipo,numero_equipo:eq.numero_equipo,proyecto:eq.proyecto,zona:eq.zona_oficial||eq.zona_operativa,mtbc_anio_actual:mtbc(ticketsYear(t),currentYearDays(),1),mtbc_u365:mtbc(periodTickets(t,365,now()),365,1)};});return{ok:true,source:'lab-sqlite',...paginate(rows,query,100)};}
  function mtbcProyectos(userId,query,candidateDb){const db=dbOr(candidateDb),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),by=new Map();portfolio.forEach(eq=>{const key=txt(eq.proyecto);if(!by.has(key))by.set(key,[]);by.get(key).push(eq);});let rows=[...by.entries()].map(([project,equipment])=>{const t=equipment.flatMap(eq=>map.get(txt(eq.numero_equipo))||[]);return{proyecto:project,equipos:equipment.length,mtbc_anio_actual:mtbc(ticketsYear(t),currentYearDays(),equipment.length),mtbc_u365:mtbc(periodTickets(t,365,now()),365,equipment.length)};});const needle=upper(query?.proyecto);if(needle)rows=rows.filter(r=>upper(r.proyecto).includes(needle));return{ok:true,source:'lab-sqlite',...paginate(rows,query,100)};}
  function u365Equipos(userId,query,candidateDb){const db=dbOr(candidateDb),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),rows=portfolio.map(eq=>{const t=periodTickets(map.get(txt(eq.numero_equipo))||[],365,now()),b=blt(t),c=client(t);return{codigo_equipo:eq.numero_equipo,numero_equipo:eq.numero_equipo,proyecto:eq.proyecto,zona:eq.zona_oficial||eq.zona_operativa,llamadas_365d:t.length,fallas_blt_365d:b.length,llamadas_cliente_365d:c.length,ultima_blt:latestDate(b),mtbc_u365:mtbc(t,365,1)};}).sort((a,b)=>b.llamadas_365d-a.llamadas_365d);return{ok:true,source:'lab-sqlite',...paginate(rows,query,100)};}
  function u365Proyectos(userId,query,candidateDb){const db=dbOr(candidateDb),portfolio=root.ManttoLabOperationService.activeInServicePortfolio(userId,db),map=ticketMap(userId,db),by=new Map();portfolio.forEach(eq=>{if(!by.has(eq.proyecto))by.set(eq.proyecto,[]);by.get(eq.proyecto).push(eq);});const rows=[...by.entries()].map(([project,eqs])=>{const t=periodTickets(eqs.flatMap(eq=>map.get(txt(eq.numero_equipo))||[]),365,now()),b=blt(t);return{proyecto:project,equipos:eqs.length,llamadas_365d:t.length,fallas_blt_365d:b.length,ultima_blt:latestDate(b),mtbc_u365:mtbc(t,365,eqs.length)};}).sort((a,b)=>b.llamadas_365d-a.llamadas_365d);return{ok:true,source:'lab-sqlite',...paginate(rows,query,100)};}
  function criticidadCorporativa(userId,candidateDb){const eq=equipmentRows(userId,{dias:365,min_fallas:3},candidateDb).rows,pro=projectRows(userId,{dias:365,min_fallas:5,min_fallas_equipo:3},candidateDb).rows;return{ok:true,source:'lab-sqlite',data:{equipos:eq.map(r=>r.codigo_equipo),proyectos:pro.map(r=>r.proyecto),criterios:{equipos:{dias:365,min_fallas:3},proyectos:{dias:365,min_fallas:5,min_fallas_equipo:3}}}};}
  return Object.freeze({prefs,equiposCriticos,equipoTickets,proyectosCriticos,proyectoTickets,mtbcEquipos,mtbcProyectos,u365Equipos,u365Proyectos,criticidadCorporativa,equipmentRows,projectRows});
});
