(function initManttoLabDiagnosticsService(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.ManttoLabDiagnosticsService=api;})(typeof globalThis!=='undefined'?globalThis:this,function createManttoLabDiagnosticsService(root){
'use strict';
const VERSION='FASE_10_LAB_DGB_SERVICIOS_TRANSVERSALES_CIERRE_V002';
function dbOr(candidate){const db=candidate||root?.ManttoLabDB;if(!db||typeof db.query!=='function')throw new Error('MANTTO_LAB_DB_REQUIRED');return db;}
function roleRows(userId,db){const id=Number(userId||0);if(!id)return[];return db.query(`SELECT DISTINCT r.id_rol,r.rol,r.codigo,r.empresa FROM roles r WHERE r.estado=1 AND (r.id_rol=(SELECT rol_id FROM usuarios WHERE id_SB=? LIMIT 1) OR r.id_rol IN (SELECT id_rol FROM usuario_roles WHERE id_usuario=? AND activo=1)) ORDER BY r.id_rol`,[id,id]);}
function isProgrammer(user,candidateDb){const db=dbOr(candidateDb),id=Number(user?.id_SB||user?.id||0);return roleRows(id,db).some(row=>{const code=String(row.codigo||'').trim().toUpperCase(),name=String(row.rol||'').trim().toUpperCase();return code==='PROGRAMADOR'||code==='PROGRAMADOR_UNITED'||code==='PROGRAMADOR_CORELLIAN'||name==='PROGRAMADOR'||name==='PROGRAMADOR UNITED'||name==='PROGRAMADOR CORELLIAN';});}
function assertProgrammer(user,candidateDb){if(!isProgrammer(user,candidateDb))throw Object.assign(new Error('Los diagnósticos técnicos del LAB son exclusivos de Programador.'),{status:403,code:'LAB_PROGRAMMER_ONLY'});return true;}
function routeCoverage(){const routes=root?.ManttoLabBackend?.listRoutes?.()||[];const byMethod={};const byArea={};for(const route of routes){byMethod[route.method]=(byMethod[route.method]||0)+1;const area=String(route.path||'/').split('/').filter(Boolean)[1]||'root';byArea[area]=(byArea[area]||0)+1;}return{total:routes.length,byMethod,byArea,routes};}
async function health(candidateDb){const db=dbOr(candidateDb),stats=db.databaseStatistics(),blobs=root?.ManttoLabBlobStore?.list?await root.ManttoLabBlobStore.list():[];return{ok:Number(stats.foreignKeyViolations||0)===0&&Number(stats.sqliteUserVersion||0)>=10,version:VERSION,lineage:'LAB_DGB_V2',database:stats,blobStore:{count:blobs.length,bytes:blobs.reduce((sum,row)=>sum+Number(row.size||0),0)},backend:root?.ManttoLabBackend?.getStatus?.()||null,transport:root?.ManttoLabTransport?.getStatus?.()||null,pwa:root?.ManttoLabPwa?.getStatus?.()||{supported:false,registered:false},jobs:root?.ManttoLabJobsService?.status?.()||null,productionConnectionsAllowed:false};}
async function closure(candidateDb){const h=await health(candidateDb),coverage=routeCoverage(),backup=root?.ManttoLabBackupService?.summary?await root.ManttoLabBackupService.summary({db:candidateDb||root.ManttoLabDB}):null;return{ready:h.ok,version:VERSION,lineage:'LAB_DGB_V2',userVersion:Number(h.database.sqliteUserVersion||0),tables:Number(h.database.tables||0),foreignKeyViolations:Number(h.database.foreignKeyViolations||0),routes:coverage.total,backup,pwa:h.pwa,jobs:h.jobs,productionConnectionsAllowed:false,externalApplicationApis:false};}
return Object.freeze({VERSION,roleRows,isProgrammer,assertProgrammer,routeCoverage,health,closure});
});
