'use strict';
const CACHE_NAME='mantto-lab-dgb-v2-phase11-20260917';
const SHELL=[
 './index.html','./manifest.webmanifest','./icons/lab-icon.svg','./styles/lab-phase1.css','./styles/lab-phase4.css',
 './vendor/sql.js/1.14.2/sql-wasm.js','./vendor/sql.js/1.14.2/sql-wasm.wasm',
 './database/version.json','./database/schema.sql','./database/seed.sql',
 './database/migrations/004_permissions_catalog.sql','./database/migrations/005_shared_services.sql','./database/migrations/006_home_services.sql','./database/migrations/007_operation_portfolio.sql','./database/migrations/008_sales_collections.sql','./database/migrations/009_installations_logistics_warehouse.sql','./database/migrations/010_technical_closure.sql','./database/migrations/011_informes_traslado.sql',
 './runtime/lab-db.js','./runtime/lab-bootstrap.js','./runtime/lab-backend-bootstrap.js','./runtime/lab-transport.js','./runtime/lab-phase4-bootstrap.js','./runtime/lab-phase5-bootstrap.js','./runtime/lab-phase6-bootstrap.js','./runtime/lab-phase7-bootstrap.js','./runtime/lab-phase8-bootstrap.js','./runtime/lab-phase9-bootstrap.js','./runtime/lab-phase10-bootstrap.js','./runtime/lab-phase11-informes-bootstrap.js','./runtime/lab-pwa.js','./runtime/lab-auth.js',
 './backend/lab-errors.js','./backend/lab-context.js','./backend/lab-router.js','./backend/lab-backend.js',
 './backend/routes/lab-system.routes.js','./backend/routes/lab-auth-permissions.routes.js','./backend/routes/lab-shared.routes.js','./backend/routes/lab-home.routes.js','./backend/routes/lab-operation.routes.js','./backend/routes/lab-sales-collections.routes.js','./backend/routes/lab-installations-logistics-warehouse.routes.js','./backend/routes/lab-technical.routes.js',
 './backend/services/lab-permissions.service.js','./backend/services/lab-scope.service.js','./backend/services/lab-catalogs.service.js','./backend/services/lab-users.service.js','./backend/services/lab-relations.service.js','./backend/services/lab-shared-assets.service.js','./backend/services/lab-blob-store.js','./backend/services/lab-interactions.service.js','./backend/services/lab-notifications.service.js','./backend/services/lab-tasks.service.js','./backend/services/lab-home.service.js','./backend/services/lab-operation.service.js','./backend/services/lab-criticals.service.js','./backend/services/lab-informes.service.js','./backend/services/lab-portfolio.service.js','./backend/services/lab-movements.service.js','./backend/services/lab-followup.service.js','./backend/services/lab-tickets.service.js','./backend/services/lab-sales.service.js','./backend/services/lab-collections-uni.service.js','./backend/services/lab-collections-cor.service.js','./backend/services/lab-installations.service.js','./backend/services/lab-logistics.service.js','./backend/services/lab-warehouse.service.js','./backend/services/lab-backup.service.js','./backend/services/lab-jobs.service.js','./backend/services/lab-diagnostics.service.js',
 '../core/rich-text.js'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('mantto-lab-dgb-')&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.includes('/api/'))return;event.respondWith((async()=>{const cached=await caches.match(request);if(cached)return cached;try{const response=await fetch(request);if(response&&response.ok&&(url.pathname.includes('/lab/')||url.pathname.endsWith('/core/rich-text.js'))){const cache=await caches.open(CACHE_NAME);cache.put(request,response.clone());}return response;}catch(error){if(request.mode==='navigate'){const fallback=await caches.match('./index.html');if(fallback)return fallback;}throw error;}})());});
